### ISSUE TITLE
Convert the ipynb to a markdown notebook, for consistency.

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#106]
https://myst-nb.readthedocs.io/en/latest/authoring/basics.html#text-based-notebooks

**Comment by christophfink** [comment]
Could be carried out together with issue #80

**Comment by HTenkanen** [comment]
> https://myst-nb.readthedocs.io/en/latest/authoring/basics.html#text-based-notebooks

This looks interesting and is definitely more version control friendly. 👍🏻 I guess a good approach here might be to follow the approach how we have setup the [Jupytext with our book](https://github.com/Python-GIS-book/site/blob/master/CONTRIBUTION_GUIDELINES.md#sync-jupyter-notebook-with-myst_markdown) having both the Notebook and the Markdown. 

There are some caveats still if going fully markdown (i.e. not having Notebooks at all): 1) writing code-documentation with pure Markdown is quite annoying experience (have done this for a couple of years, way back). Basically one would anyway do it in a way that you first write a Notebook, and then convert it to Markdown. 2) For users of the library, it might also be nice to have the possibility to download a Notebook that we have written for the usage and just start playing around with it, without the need for any command-line conversions in between. 

Hence, although I definitely see the benefits of going fully Markdown, I think it might still be a good idea to not fully forget the Notebooks as a format. In addition, we do still seem to have issues being able to execute the Notebook cells using `myst_nb` which is a requirement for this to work in the first place: https://r5py.readthedocs.io/en/latest/basic-usage.html
