### ISSUE TITLE
notebook cell times out on RTD

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#107]
It did not, but the fix should be easy (had to do the same locally)
```
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
```

https://r5py.readthedocs.io/en/latest/reports/basic-usage.log 

I’ll go ahead an create a new issue and push a fix :)

_Originally posted by @christophfink in https://github.com/r5py/r5py/issues/104#issuecomment-1131732762_

**Comment by HTenkanen** [comment]
Aha, okay well this is an easy fix if it was just this! 🙂
