### ISSUE TITLE
Build badge does not work anymore

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#112]
Since the accidental deletion and restoration of the repository, the badge showing the workflow status seems to have stopped working: 
https://github.com/r5py/r5py/actions/workflows/build-merged-pull-requests.yml/badge.svg 

![badge](https://user-images.githubusercontent.com/4998473/169341700-6dafcf2b-3c4d-4260-bd6c-b10ed63b725f.svg)

@HTenkanen could you ask support whether this is connected? Thanks :)

**Comment by HTenkanen** [comment]
Left a support ticket about this.

**Comment by HTenkanen** [comment]
@christophfink Got a reply about this:

> It turns out Github Badges ignores statuses from forked pull requests. The majority of runs are from forks:
https://github.com/r5py/r5py/actions/workflows/build-merged-pull-requests.yml
Sorry about that. Please let us know if you have any other questions.

If I understand this correctly, the support seems to suggest that we should commit something from a branch in the main repository. Not sure if this works, but we could try.

**Comment by christophfink** [comment]
Oh, now that’s odd. At latest when we build the next release, that’s going to happen in `main` :)

**Comment by HTenkanen** [comment]
Yep, a bit odd, but let's see if the next release fixes this.
