### ISSUE TITLE
Make binder checkout stable or latest

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#123]
Depending on from where as user clicks the binder link, direct them to a notebook that uses the latest or the stable code base.

see discussion in PR #118 

> I’m thinking that the version should always be the correct one without any added configuration, if we simply have the notebooks load `r5py` from the `src` directory. No need to automate anything, then - or am I thinking this wrongly? RTD is always referencing the respective stable or latest code. So simply changing the `sys.path` to keep pointing to the source directory works for RTD and locally cloned repos.
> 
> When it comes to binder, we should maybe take it into a new issue, because this here is about jupytext. This is getting a bit too complex and off-topic for my taste in this PR.

_Originally posted by @christophfink in https://github.com/r5py/r5py/pull/118#discussion_r879352334_

**Comment by christophfink** [comment]
Not quite sure whether `html_theme_options["repository_branch"]` in `conf.py` can, in fact, point to a tag: https://sphinx-book-theme.readthedocs.io/en/stable/customize/index.html?highlight=html_theme_options#theme-options

**Comment by christophfink** [comment]
duplicate of #122

**Comment by HTenkanen** [comment]
> Not quite sure whether `html_theme_options["repository_branch"]` in `conf.py` can, in fact, point to a tag: https://sphinx-book-theme.readthedocs.io/en/stable/customize/index.html?highlight=html_theme_options#theme-options

Let's continue in the other issue, but answering to this still here: I tested this and it is possible to configure Binder to use a tag. So this is not `sphinx-book-theme` specific thing at all, but actually related to how binder works. The theme (i.e. the things we configure in conf.py, just creates a link with specific structure. In the [mybinder.org](https://mybinder.org/), you can add a branch/tag or even a specific commit):
![image](https://user-images.githubusercontent.com/6659534/169815639-df8f0b79-14b1-4aad-893d-5f3978bbe8ca.png)
