### ISSUE TITLE
Question: Filter Pycharm keys from Notebook metadata using nbstripout?

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#126]
@christophfink : Did we already have some automation in terms of `nbstripout`? It seems that it is possible to use nbstripout to remove specific metadata, and it would be great if we could strip out `pycharm` related clutter from the Notebooks: https://github.com/kynan/nbstripout#stripping-metadata

As you understand better how nbstripout works, couple of questions:
- Can we add the metadata related rules to the `.gitattributes`? OR
- Do I just need to configure this locally using the `git config ...` commands as instructed in the docs?

**Comment by HTenkanen** [comment]
At least the local configuration works using the `git config` and then running `nbstripout` from terminal

**Comment by christophfink** [comment]
Feel free to add it to .gitattributes (there should be an nbstripout rule in there, but does it currently work properly?)

**Comment by HTenkanen** [comment]
I'm not sure how the .gitattributes / nbstripout should be used appropriately? I guess atm it is my responsibility to run `nbstripout` before committing stuff to git for it to work properly? 

I see there is possibility to add a pre-commit hook for nbstripout but I guess we don't have that in place (?):
https://github.com/kynan/nbstripout#using-nbstripout-as-a-pre-commit-hook

**Comment by christophfink** [comment]
This is in https://github.com/r5py/r5py/blob/main/.gitattributes

**Comment by christophfink** [comment]
It should run as a git filter (which does not have extra dependencies, like pre-commit, but I'm not sure *when* it runs in a commi workflow)

**Comment by HTenkanen** [comment]
Right, need to make a test commit to see whether this works 👍🏻

**Comment by christophfink** [comment]
No sure whether it simple has to be in $PATH, or there's something else to configure, still. It definitely worked before, in this repo.

**Comment by christophfink** [comment]
> The .gitattributes file affects everyone who clones the repository since it’s committed to the repository. However, the filter definition – what munge-project-identifier means – is not. If someone’s git config does not define that filter, this attribute won’t do anything. This means that everyone gets the .gitattributes, but actually applying the filter is opt-in. 

https://bignerdranch.com/blog/git-smudge-and-clean-filters-making-changes-so-you-dont-have-to/

**Comment by christophfink** [comment]
Although it might be that our .gitattributes actually defines those inline ...

**Comment by christophfink** [comment]
Not sure whether this can be fixed easily. I’m not exactly excited about pre-commit.io, it seems rather bloated and it would require us to give write permissions to the repo to a(nother) third party service. Maybe we can close this for now, and come back to it if we discover that we frequently forget to run nbstripout and jupytext (for those, it would be great).
