### ISSUE TITLE
`share_of_ram()` possibly returns negative values 

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#127]
While writing the tests, spotted an issue. If user requests with `leave_at_least` parameter more memory than actually exists on the user's computer, the function will return a negative value:
https://github.com/r5py/r5py/blob/main/src/r5py/util/memory_footprint.py#L59

This probably doesn't cause any issues at the moment and this function is not something that users are likely to use for anything, but still I think fixing this logic would make sense: i.e. return 0 and perhaps also raise an exception if memory cannot be allocated to the tool at all.

**Comment by christophfink** [comment]
Related to #120 (which works around this, so the issue never surfaces, but clamping share_of_ram()s output to >=0 would make sense)

**Comment by christophfink** [comment]
This has been fixed in 976b1720
