### ISSUE TITLE
`max_memory` without specified unit expects the input in kilobytes? 

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#129]
I believe these lines [expect the input in kilobytes](https://github.com/r5py/r5py/blob/main/src/r5py/util/memory_footprint.py#L72-L76)? Is this expected behavior? 

It would be good to improve the [docstring](https://github.com/r5py/r5py/blob/main/src/r5py/util/memory_footprint.py#L64) about expected/possible inputs.

**Comment by christophfink** [comment]
It should be in bytes, see the description of the argparse argument further up in the same file. You can also copy that to the docstring

**Comment by HTenkanen** [comment]
> It should be in bytes, see the description of the argparse argument further up in the same file. You can also copy that to the docstring

Okay, well in this case, if I'm not wrong, there is a bug here because the logic to convert bytes to Megabytes expects input in kilobytes (not bytes) to return input value to megabytes.

**Comment by christophfink** [comment]
Yes, you're right, line 74 should multiply by 2**-20

**Comment by HTenkanen** [comment]
> the description of the argparse argument further up in the same file.

Ah right, didn't realize to look from there. Should we also add the docstring to this function? At least I didn't realize to search from there, so wouldn't be surprised if someone misses this as well.

**Comment by christophfink** [comment]
Good that we write tests :+1:

**Comment by HTenkanen** [comment]
Yep, the tests are excellent for spotting these kind of small issues that are hard to find without testing 🙂

**Comment by christophfink** [comment]
Yes, either add a docstring (preferable), or give it a private name (_max_memory). Also thought that this function now does two things at the same time. Should we refactor it to two functions (one parsing the input, one to clamp the values to >ABSOLUTE_MIN)?

**Comment by christophfink** [comment]
Also, should we add a 'K' unit, still, for consistency?

**Comment by HTenkanen** [comment]
> Yes, either add a docstring (preferable), or give it a private name (_max_memory). Also thought that this function now does two things at the same time. Should we refactor it to two functions (one parsing the input, one to clamp the values to >ABSOLUTE_MIN)?

Yep a good point. A good practice would be to split this into separate functions, so 👍🏻 doing the change from me. 

> Also, should we add a 'K' unit, still, for consistency?

Yes, would make sense!

**Comment by christophfink** [comment]
Also, I left the elif unit == "M" line in there as a reference that it is a noop line, maybe we should uncomment it?

**Comment by HTenkanen** [comment]
I can work on these now as I'm anyway on these things while writing the tests.

**Comment by christophfink** [comment]
I don’t see the problem, the regex matches fine:

```
import re
inputs = ["2097152", "2048K", "2M", "1.5G", "0.2T", "25%"]
for input in inputs:
    matches = re.match(r"(?P<value>[0-9]+(\.[0-9]+)?)(?P<unit>[%KMGT])?", input)
    print(matches, matches["value"], matches["unit"])
```

results in

```
<re.Match object; span=(0, 7), match='2097152'> 2097152 None
<re.Match object; span=(0, 5), match='2048K'> 2048 K
<re.Match object; span=(0, 2), match='2M'> 2 M
<re.Match object; span=(0, 4), match='1.5G'> 1.5 G
<re.Match object; span=(0, 4), match='0.2T'> 0.2 T
<re.Match object; span=(0, 3), match='25%'> 25 %
```

**Comment by christophfink** [comment]
Oh I did not read correctly, sorry. 
But this still can be changed to match any letter there and tell about it.

**Comment by HTenkanen** [comment]
Yep, there are different ways to handle this, but I think the bottom line is that should be enforce the user to specify the unit for memory?

**Comment by christophfink** [comment]
```
import re
inputs = ["2097152", "2048K", "2M", "1.5G", "0.2T", "25%", "123J"]
for input in inputs:
    matches = re.match(r"(?P<value>[0-9]+(\.[0-9]+)?)(?P<unit>[^0-9])?", input)
    unit = matches["unit"]
    value = matches["value"]
    print(matches, value, unit)
    if (
    	unit is not None
    	and unit not in "%KMGT"
    ):
    	raise ValueError(f"Suffix {unit} not understood")
```

**Comment by HTenkanen** [comment]
@christophfink : Pushed now my suggestion in #131

**Comment by HTenkanen** [comment]
> Then we allow non-suffixes, but still prevent wrong ones

We can do this as well, but I'm not sure whether it is a good practice to allow passing just a number. If we would allow in the end to provide just a number, then would it make more sense to default to some other unit than bytes? I doubt no-one ever passes any numbers in bytes after all. :) More intuitive would perhaps be MiB.

**Comment by christophfink** [comment]
the none-prefixed value should be bytes, anything else would be weird by SI/IEC and also powers-of-two series.

**Comment by christophfink** [comment]
I know this is a bit of an edge case, but I can totally see applications where this memory limit is calculated somewhere else in the pipeline, and comes as a number. Due to Unix/Posix conventions, we already have to go the detour via strings, but still forcing an additional suffix makes things unlogical and prone to error.

**Comment by HTenkanen** [comment]
Okay, fair enough if you see that there is a real use-case for this. Will keep the bytes possibility in.
