### ISSUE TITLE
Publish at conda-forge?

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#13]
@christophfink: I think it would be good to publish this also at conda-forge. I can write a recipe if you wish?

**Comment by christophfink** [comment]
That would be absolutely great! I’ve never used it myself, but I know that many people prefer conda over PyPi. 
Could you create a pull request? It would be best to add it to the https://github.com/r5py/r5py/blob/main/.github/workflows/release-and-deploy-v-tags.yml workflow that is triggered when a new `v0.0.0` tag is created. Could you then also add the conda installation command to the README?

**Comment by HTenkanen** [comment]
@christophfink: Sure thing. And definitely I think all the contributions should happen via forks/PRs. Also suggested adding these instructions, see #16

**Comment by christophfink** [comment]
I like the way you set the ground rules and describe contribution modalities for pyrosm. Maybe we could take some ideas from there? ;)

**Comment by HTenkanen** [comment]
Yeah, sure 👍🏻

**Comment by christophfink** [comment]
So it would be nice if we could have a deployable version by maybe this or next week, so we secure the package name ;)

**Comment by HTenkanen** [comment]
Ah, right, well definitely let's aim to push the first version to PyPi asap. I thought the v0.0.2 was already on PyPi. I guess it wouldn't harm if we already release that one to secure the project name? 

It's not like someone would immediately find the package start using it, and we can soon release the next version. For conda-forge it would be good to have the package in PyPi (not necessary but easier).

**Comment by christophfink** [comment]
Let’s try to close the three currently open pull requests (#45 #54 #56 ; all of them build clean, I think) in the morning, and tag a new `v0.0.3` after that.

**Comment by HTenkanen** [comment]
@christophfink: Related to conda-forge recipe, I guess the r5py itself (at least at this point) will be pure Python and won't have any C/Cython code that should be compiled? I.e. we could go with [noarch: python](https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python) directive?

**Comment by christophfink** [comment]
Yes, that's correct, its pure Python (and I don't see how we could make significant gains by introducing, e.g., Cython; the heavy lifting is done in Java, anyway; guess for the foreseeable future, it's going to stay pure python)
The PyPi package has the classifier of being OS-independent.

**Comment by HTenkanen** [comment]
Yes this is what I thought and added the noarch directive 👍🏻 Now should be ready with the script.

**Comment by HTenkanen** [comment]
@christophfink : FYI, I added you as the recipe maintainer as well. I hope that is okay?

**Comment by christophfink** [comment]
Thanks! That’s of course very welcome!

For the record, I also added you as a package owner on PyPi (which you have already accepted :smile: )

**Comment by HTenkanen** [comment]
Yes, thanks saw that! 🙂

**Comment by HTenkanen** [comment]
FYI: There is some queue at conda-forge (as expected), so it might take a few days to get our feedstock reviewed and accepted.

**Comment by christophfink** [comment]
Works!
