### ISSUE TITLE
Maximum number of percentiles allowed is 5

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#139]
Seems like R5 only allows a maximum of 5 percentiles. Would be something we should check on input (`len(percentiles) < 5`) and throw an error before the VM starts up to save folks time.

```
java.lang.java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Maximum number of percentiles allowed is 5
```

I can look into figuring out how to make this happen. Calling it a "bug" at this point but a mild one at that. Perhaps documentation?

**Comment by christophfink** [comment]
Good catch, I didn’t realise R5 has this limitation. We could definitely add a check there.
