### ISSUE TITLE
Check that input data has unique id columns

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#140]
We should make sure the input origins for travel time computation includes unique ID columns. Just tried to run it with non-unique IDs and got the following error:

```
  File "...\pandas\core\series.py", line 191, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>
```
I wonder if we should provide an option for the user to specify the unique ID column also.

**Comment by HTenkanen** [comment]
Yeah, we might want to add a couple of assertions to ensure the ids are unique. Also adding possibility to define the id column is a good idea to give a bit of flexibility to the user 👍🏻 

In addition, I'm thinking whether it would make sense to automatically create the ids based on row numbers. Perhaps not (can probably cause more issues/confusion than help), but it would be a rather trivial thing to do.

**Comment by wklumpen** [comment]
> In addition, I'm thinking whether it would make sense to automatically create the ids based on row numbers. Perhaps not (can probably cause more issues/confusion than help), but it would be a rather trivial thing to do.

The danger here is we generate TT matrices with auto-generated IDs and the user thinks it's referring to something else? If we're going to do this I would suggest being pretty obvious about it like `auto01` or something

**Comment by HTenkanen** [comment]
> > In addition, I'm thinking whether it would make sense to automatically create the ids based on row numbers. Perhaps not (can probably cause more issues/confusion than help), but it would be a rather trivial thing to do.
> 
> The danger here is we generate TT matrices with auto-generated IDs and the user thinks it's referring to something else? If we're going to do this I would suggest being pretty obvious about it like `auto01` or something

Perhaps we could skip this option for now at least. I see it probably causing more harm than benefits.

**Comment by christophfink** [comment]
Reverted the merge, this should not have gone into main, yet

**Comment by christophfink** [comment]
I removed it from the milestone, instead, if that was your motivation @HTenkanen ?
