### ISSUE TITLE
Add a test dataset for frequency based GTFS from Sao Paolo

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#143]
@christophfink @rafapereirabr @wklumpen 

Let's add a frequency based GTFS dataset from Sao Paolo which is also used in r5r for testing purposes. In this way, we can also compare between packages performance, results etc.

**Comment by christophfink** [comment]
for reference, we’re talking about this data set: https://github.com/ipeaGIT/r5r/tree/master/r-package/inst/extdata/spo

@rafapereirabr : what’s the license of this, can we include it over here? It’s also mentioned in https://github.com/ipeaGIT/r5r/blob/master/r-package/paper2021/paper2021.Rmd, but more details (origin, license) would be great :)

**Comment by rafapereirabr** [comment]
Hi all. The GTFS for São Paulo comes from the [local public transport agency SPTrans open data website](https://www.sptrans.com.br/desenvolvedores/). They don't put any explicit license on their website. However, this is an open data set about a plublic service and the data set is publicly shared by a governmental transport agency. I'm certain there is no problem in sharing the data in the package. 

In the case of r5r, we created a subset of the original GTFS feed to reduce the file size. If you want to, I could upload our file in r5py. I just need to know in which directory I should place the GTFS and OSM files.

**Comment by christophfink** [comment]
@rafapereirabr that would be fantastic! For the time being, please put the sample data into `docs/data/` (that way it is checked out together with the notebooks, e.g., to binder).

If you could open a pull request, I could then rename the existing GTFS data set (from Helsinki) and change all the references in notebooks etc., before merging it.

**Comment by rafapereirabr** [comment]
Sorry for the long wait. I just created a pull request with the data #145 .
