### ISSUE TITLE
Keep more control of what the output from `TravelTimeMatrixComputer` returns

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#144]
@christophfink @rafapereirabr @wklumpen : 

We had a discussion about r5py and one of the things that Rafa pointed out based on their experience with r5r is that it might be good if we would add a bit stricter control for what inputs user can pass to `TravelTimeComputer` (or add separate functions using the class). The issue is that currently a user can pass any arguments accepted by `RegionalTask` to `TravelTimeComputer` and depending of what the user passes (e.g. `breakdown=True/False`), the output from the tool can be very different. Because of this r5r has two separate functions that has control of what the tool will produce as a result. For reference, see the `travel_time_matrix()` and `expanded_travel_time_maxtrix()` functions in here:
https://ipeagit.github.io/r5r/articles/travel_time_matrix.html 

In my opinion, this is a valid concern and we might want to implement something similar to make it easier to document for the users as well as to maintain.

Any thoughts?

**Comment by wklumpen** [comment]
Sounds like based on our call we want to go with a similar design to r5r with the two function calls. I would also agree that having a consistent output for functions like this is pretty important.

**Comment by christophfink** [comment]
Yes. I absolutely think we should go that way. However, it would be smart to implement these changes on top of R5 v6.7, which requires some changes to the existing code (how the transport network is loaded, for instance). Maybe we can open another issue concerning the R5 version-bump that should be sorted out first.

**Comment by wklumpen** [comment]
I wish there was a good way to show "depends on another issue" in GitHub - perhaps we can add a "blocked" tag so things don't get worked on out of order?

**Comment by HTenkanen** [comment]
> For the sake of completeness: what @HTenkanen attributes to `expanded_travel_time_matrix` is, in fact, handled by `detailed_itinerearies` in r5r: https://ipeagit.github.io/r5r/reference/detailed_itineraries.html
> 
> This is also to say that PR #138 is implementing the latter, but not yet the former.

You're absolutely right, I meant the `detailed_itineraries` 👍🏻
