### ISSUE TITLE
Testing: Include Coverage for tests?

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#15]
I at least find it useful to include coverage for tests, as it helps out understanding where we stand in terms of testing. I can configure this if we think it would be useful?

https://coverage.readthedocs.io/en/6.3.2/

**Comment by christophfink** [comment]
yes, as soon as we have tests :-D currently, coverage is at 0%
(let’s talk about that in our meeting)

**Comment by HTenkanen** [comment]
Haha, yes. 🙂 It's a good place to start, the only direction is ⬆️ 😄

**Comment by HTenkanen** [comment]
Ah, I actually referred to wrong package. I meant pytest-cov package and configure the Coverage reporting for the package which would provide the badge. Many have configured/use codecov.io (incl. myself with pyrosm): https://about.codecov.io/

**Comment by christophfink** [comment]
Aaaah! that makes sense. tox runs pytest-cov (`pytest --cov ...`) already in my pull request, but maybe we can combine this straight with the matrix testing, and upload to codecov.io
