### ISSUE TITLE
Bump R5 version to 6.7 or 6.8 (to be released soonish?)

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#154]
_Originally posted by @christophfink in https://github.com/r5py/r5py/issues/144#issuecomment-1216771476_

**Comment by christophfink** [comment]
consider #43 !

**Comment by HTenkanen** [comment]
Considering the effects of #43, I believe bumping the R5 version before the next release is unlikely to happen.. Hence, I will remove this issue from the Milestone at this stage.

**Comment by christophfink** [comment]
It would be good to still do this, but, on the other hand, maybe it’s better to release a not-perfect version before your conference next week.

**Comment by HTenkanen** [comment]
@christophfink : Yup, I should also be teaching this next week in Augsburg, so I would very much like to have a release rather soon that we could use with the current functionality..
