### ISSUE TITLE
Warn if the user specifies a date that is outside of the GTFS time extent 

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#157]
We should give a warning for the user in the following case: I specified a date that was out of the time window of the GTFS feed. This caused that only the walking mode was effective during the routings. This can cause confusion as r5py doesn't give any warnings about not being able to route at specific date using transit network. In these cases only walking times are returned as results (until the `max_time` threshold is hit).

**Comment by wklumpen** [comment]
Wow I had assumed this was something R5 would handle itself. I wrote some basic code to do that over at `gtfs-lite`: https://github.com/wklumpen/gtfs-lite

Here's the function: https://github.com/wklumpen/gtfs-lite/blob/ba13d200127a0a0977c1119bc1c63ee07aea6f61/gtfslite/gtfs.py#L409
