### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#17]
It might also be good to add a code of conduct in a similar manner as how geopandas does it: https://geopandas.org/en/stable/community/code_of_conduct.html

**Comment by wklumpen** [comment]
I can do this - I assume it would sit in the docs?

**Comment by christophfink** [comment]
There’s a location suggested by GitHub community standards: https://github.com/r5py/r5py/community

**Comment by HTenkanen** [comment]
> I can do this - I assume it would sit in the docs?

@christophfink: Actually, I believe it would be good to put this document inside the `docs` directory because we want to include this document to the website as well, and Sphinx doesn't seem to support adding files that are "above" the `docs` folder (i.e. on project root).

**Comment by christophfink** [comment]
Does that allow us to somehow also make GitHub see that we added a Code of Conduct? (so we get the green check mark there :D)

**Comment by HTenkanen** [comment]
@christophfink : Yes, Github detects all files stored in docs folder and root (there was a third location as well but don't remember what it was)

**Comment by HTenkanen** [comment]
This is now merged to main by #87
