### ISSUE TITLE
Do we want to add a helper function to download the test data for r5py?

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#178]
@christophfink While writing the basic usage docs, I realize that it's a bit awkward to get the test datasets available (PBF + GTFS) for `r5py`. I was wondering that should we perhaps implement a simple helper function in a similar manner as e.g. in `pyrosm` or `geopandas` to download the sample files to `TEMP` from our repo, or from a gist.

The files are so large that we don't want to bundle them directly with the package, but this kind of simple helper function would do the trick. This is not a problem for getting the docs to work, but when demonstrating the usage for someone who has just installed the package, it's a bit tricky to quickly get started. 

Any thoughts on this? I could quickly implement this as have done it already once for `pyrosm`. We could serve the data this way both for Helsinki and Sao Paolo.

**Comment by christophfink** [comment]
We could also retrieve the test data on-the-fly (does geopandas accept URLs?).
I have this requests session wrapper somewhere that’s similar to the `ValidatingRequestsSession` in `r5py.util` that caches files locally. 

Either way, definitely a good idea that we should keep in mind. Not sure where it should go to (were you thinking of something like `r5py.util.download_test_data()`?), or whether we simply add a link in the documentation?

**Comment by HTenkanen** [comment]
> test data on-the-fly (does geopandas accept URLs?)

Geopandas does accept URLs, but I guess the issues is more with the PBF + GTFS files as I guess R5 doesn't accept URLs?

> Either way, definitely a good idea that we should keep in mind. Not sure where it should go to (were you thinking of something like r5py.util.download_test_data()?), or whether we simply add a link in the documentation?

Yep it would definitely be a utility function, so a separate file under the `util` would make sense.

**Comment by rafapereirabr** [comment]
I thought the test was was shipped with the package, like in R packages. If that is not the case, I suggest we add the data files as additional 'Assets' to the github release. This would make it easier to create something like a `r5py.util.download_test_data()` function.

**Comment by HTenkanen** [comment]
> I thought the test was was shipped with the package, like in R packages. If that is not the case, I suggest we add the data files as additional 'Assets' to the github release. This would make it easier to create something like a `r5py.util.download_test_data()` function.

Yes, often the test data is bundled with the release (like with `pyrosm`). However, the GTFS and PBF files are fairly large in size, hence to avoid making the package unnecessarily large (from 30 kilobytes to several megabytes), I think it would be best to keep them separate. I.e. do something like suggested and add a helper function to download the data.

**Comment by christophfink** [comment]
It’s a bit of a discussion in the Python bubble whether or not you should include sample data with the (potentially compiled, not in our case) distribution wheels. Most arguments centre around the size of the files (there is a maximum, and I’ve previously run into it), but also on keeping code and data separated.

I’m not 100% convinced of the utility function, even (I would think instructions on how to download data in the documentation would suffice), but I guess you outvoted me on this :smile: . I would suggest to download data (and check checksums) into the CACHE directory, then defining a global `DATA_DIR` to point there.

**Comment by christophfink** [comment]
We’re using the `r5py.sampledata.*` packages since 0.1.1
