### ISSUE TITLE
Handle input CRS other than EPSG:4326

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#192]
Something that came up during the course. If the input GeoDataFrames are not in WGS84, it is not necessarily easy to spot the reason why the travel time matrix calculator does not work as expected, and returns Null values. Hence, it might be useful to add a sanity check for the CRS of input GeoDataFrames and warn or error if the coordinate reference system of the input GeoDataFrame is not suitable.

Thoughts @christophfink?

**Comment by christophfink** [comment]
That sounds like a good idea, but let’s take a step back and look at this from a bigger perspective: do we always use WGS84? (I don’t know, from the top of my head. It might be that R5 always uses it, internally)

And if we indeed always require WGS84, I think, in terms of user experience, the best would be to transparently reproject input data to WGS84, and then returned data back to the input reference system. Would you agree?

**Comment by mvpsaraiva** [comment]
> (I don’t know, from the top of my head. It might be that R5 always uses it, internally)

Coming a bit late on this: yes, R5 expects all coordinates to be in WGS 84, and I think it's because OpenStreetMap and the GTFS specification also use this CRS.

**Comment by HTenkanen** [comment]
> That sounds like a good idea, but let’s take a step back and look at this from a bigger perspective: do we always use WGS84? (I don’t know, from the top of my head. It might be that R5 always uses it, internally)
> 
> And if we indeed always require WGS84, I think, in terms of user experience, **the best would be to transparently reproject input data to WGS84, and then returned data back to the input reference system**. Would you agree?

Sorry for slow response, but I think this approach would definitely be nice for the user, i.e. that we would handle the projection stuff for the user and return the data back in the original reference system. 👍🏻 After all, doing the CRS conversions is a trivial thing. 

Have you @mvpsaraiva @rafapereirabr been considering doing something like this (i.e. handle the CRS automatically) for r5r?

**Comment by mvpsaraiva** [comment]
> Have you @mvpsaraiva @rafapereirabr been considering doing something like this (i.e. handle the CRS automatically) for r5r?

Yes, we considered doing that. But, in `r5r`, we accept regular dataframes with lat lon columns as input, which doesn't have CRS information. We planned to accept proper geodataframes only, but that would be too big of a change to do now. We only check if the lat lon values provided appear to be in degrees, and not in some projected CRS.

**Comment by rafapereirabr** [comment]
We have noticed that using regular dataframes with lat lon columns  is preferable / easier to a lot of `r5r` users, even though `r5r` accepts either dataframes and `sf` spatial objects. We understand that spatial data input is 'special' as it requires attention to projection issues, and hence requiring `sf` spatial objects wold have advantages in terms of reducing users' errors. So, in a way, there is some kind of trade-off between making the package more user friendly and making it less prone to user error.

**Comment by christophfink** [comment]
@mvpsaraiva @rafapereirabr thanks for the insights. I guess Python can be stricter here, as the geo/GIS community is quite strong. We require `geopandas.GeoDataFrames` as an input, and the conversion from a `pandas.DataFrame` with lon/lat columns is trivial (we should add that to the documentation, though -> issue #214 )

**Comment by christophfink** [comment]
#207 has been merged long ago! This is closed!
