### ISSUE TITLE
Problem occurence when running r5py in google colab environment

### ISSUE THREAD

**Issue by aldogan17** [r5py/r5py#197]
Hi, I was working on r5py on google colab environment. Colab seemed to not show any problem when importing r5py after a couple of code lines. However, when I tried to import TransportNetwork module from r5py, it simply said : 'ImportError: cannot import name 'TransportNetwork' from 'r5py' (unknown location)'. My whole code block is as follows:

!git clone https://github.com/r5py/r5py.git
%cd /content/r5py/ci
import sys
sys.argv.append(["--max-memory", "12G"])
import r5py
from r5py import TransportNetwork

transport_network = TransportNetwork(
    "../data/Helsinki/kantakaupunki.osm.pbf",
    [
        "../data/Helsinki/GTFS.zip"
    ]
)

How do you think I can solve this problem? 

Sincere thanks.

**Comment by christophfink** [comment]
Hi! Thanks for reporting this issue.

First, let me say that we don’t have experience with Google Colab, and we don’t have the capacity of supporting it. My suggestions here are guesswork; however, I hope we can together figure out what is causing this issues you’re facing.

If I understand your code correctly:
- the working directory you are trying to import r5py from is `/content/r5py/ci/`, and 
- you cloned the git repo’s `main` branch

Again, no idea how things work on Google Colab, but a fundamental thing that would fix several of the issues connected to that (system path, dependencies not installed) would be to r5py before using it. You can use pip (also from the cloned git repo) or mamba/conda. (see also https://r5py.readthedocs.io/en/stable/installation.html )

**Comment by aldogan17** [comment]
Hi, many thanks for answering. I accidentally skipped the line for installation when I was opening the issue. Here is the corrected version:

!git clone https://github.com/r5py/r5py.git
%cd /content/r5py/ci
!pip install -r r5py_distro.txt
import sys
sys.argv.append(["--max-memory", "12G"])
import r5py
from r5py import TransportNetwork

transport_network = TransportNetwork(
"../data/Helsinki/kantakaupunki.osm.pbf",
[
"../data/Helsinki/GTFS.zip"
]
)

In a nutshell:

-  I cloned the main repository,
- I copied the path where the installation requirements (necessary packages) file is stored. It is in yaml format (r5py_distro.yml) but I saved it as txt in visual studio editor before uploading it to the same folder. 
- after entering my working directory ( %cd /content/r5py/ci), I installed r5py.

Importing r5py did not give me an error after implementing these steps but modules in it cannot be reached.

**Comment by christophfink** [comment]
Sorry for asking these maybe obvious questions, but I can only try to understand step by step:

1. Did you add r5py itself to the dependency file (the `.txt`)? 
2. If not, is there a file or directory `r5py{,.*}` in `/content/r5py/ci/` that Python could mistake for r5py when importing?
3. Can you check whether you can import any other classes or submodules of r5py? (e.g., `r5py.r5` )
4. What value does `r5py.__version__` have?

**Comment by aldogan17** [comment]
1. I didn't add r5py to the file, however it was written in the text file already:
dependencies:
    - python=3.10
    - folium
    - fiona
    - geopandas
    - matplotlib
    - mapclassify
    - numpy
    - pandas
    - r5py
   2. there is a file named 'r5py_distro.yaml' beside other python files. 
   3. I checked for r5py.r5 module. It says: No module named 'r5py.r5'.
   4. the version is 0.0.4 if I am not mistaken.

**Comment by christophfink** [comment]
I think the problem is related to Google Colab defaulting to Python 3.7 (and r5py being available from 3.8). I tinkered around a bit with it, but have not really figured out how to replace Colab’s ipynb kernel. 

Found this: https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version

**Comment by aldogan17** [comment]
Thanks a lot for your efforts. I will definitely check the link. This might solve the problem.

**Comment by christophfink** [comment]
So, we now support Python 3.7, but it will not build until the next release (not yet scheduled). 
You can, however, install the main branch using pip. The following worked for me in Google Colab:

```
!pip install git+https://github.com/r5py/r5py.git
```

```
from r5py import TransportNetwork
```

**Comment by aldogan17** [comment]
Hi, thanks a lot. I tried running the lines and it showed no error.  
Best Regards.
