### ISSUE TITLE
Set up matrix testing as a GitHub action

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#20]
Because r5py is a fairly complex pieced-together thing using a Java JDK and being able to run on a range of Python versions (at least 3.8-3.10, as of this writing, probably more), and none of these things are trivial on Windows (slightly better on MacOS and Linux), it might be beneficial to extend testing to use the matrix functionality of GitHub runners to test all possible/likely combinations of Java/Python/OS.

**Comment by HTenkanen** [comment]
Yes, I think this is a very good idea and hopefully allow us to catch issues with specific versions / OS. 👍🏻
