### ISSUE TITLE
Don’t teach users by default to override the memory limits

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#211]
I feel that if the first thing in the basic tutorial is setting a custom memory limit, we’re implying to the user that that is something that needs to be done, rather than an edge case. 

I’m open to discuss whether 80% of RAM is a sensible default, but I feel we should move this into an ‘advanced’ section of the documentation. (We can, however, keep a note in the basic tutorial telling that, *if* the user wishes to set a custom RAM limit other than the default, which is ..., they have to do it before importing r5py, and here’s a link to how this is done)

**Comment by wklumpen** [comment]
I would support moving this into a "did you know" or more advanced section of the docs. I've personally not been setting that memory limit at all and had very little issues overall (in fact I should probably have boosted it for my purposes).

**Comment by christophfink** [comment]
> I would support moving this into a "did you know" or more advanced section of the docs. I've personally not been setting that memory limit at all and had very little issues overall (in fact I should probably have boosted it for my purposes).

Exactly what I had in mind. I think it’s not necessary or appropriate for the first-time user. It should be documented somewhere, however, because depending on the platform or system people are using, they might run into problems, or not use full potential (like on dedicated workstations or on virtual machines).

**Comment by christophfink** [comment]
i wonder whether that could be a part of the FAQ ('how to run r5py on (virtual) machines with small memory?')
