### ISSUE TITLE
Upgrade Jupytext in dev-environment

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#213]
There seems to be an issue with our tagged Jupytext version related to this issue: https://github.com/mwouts/jupytext/issues/964

Issue: When launching `jupyter lab` having the `jupytext=1.13.8` in the activate environment, the notebooks from the docs folder having `.jupytext.toml` file present cannot be used.

**Comment by christophfink** [comment]
Absolutely. I’m anyway a proponent of non-version-tagged requirements as the default. Do you remember why you added this fixed to a certain version, in the first place? (If there was some reason, it would be good to check whether that reason persists)

**Comment by christophfink** [comment]
While were at it, I’d advocate to remove `.jupytest.toml`, as the same configuration is in `pyproject.toml` in the project root (keep config in one place)

**Comment by HTenkanen** [comment]
> Absolutely. I’m anyway a proponent of non-version-tagged requirements as the default. Do you remember why you added this fixed to a certain version, in the first place? (If there was some reason, it would be good to check whether that reason persists)

The reason to use a fixed version is to avoid bloating the Notebooks with changes in metadata that might come because we might have different version of jupytext installed to our systems, and the jupytext updates the metadata in Notebooks..(which is kind of annoying)

**Comment by HTenkanen** [comment]
> While were at it, I’d advocate to remove `.jupytest.toml`, as the same configuration is in `pyproject.toml` in the project root (keep config in one place)

If this works, so definitely, but we need to check whether jupytext is smart enough to check the `pyproject.toml` (might well be, but I haven't checked the docs or tested this before)

**Comment by christophfink** [comment]
> > Absolutely. I’m anyway a proponent of non-version-tagged requirements as the default. Do you remember why you added this fixed to a certain version, in the first place? (If there was some reason, it would be good to check whether that reason persists)
> 
> The reason to use a fixed version is to avoid bloating the Notebooks with changes in metadata that might come because we might have different version of jupytext installed to our systems, and the jupytext updates the metadata in Notebooks..(which is kind of annoying)

fair enough

**Comment by christophfink** [comment]
> > While were at it, I’d advocate to remove `.jupytest.toml`, as the same configuration is in `pyproject.toml` in the project root (keep config in one place)
> 
> If this works, so definitely, but we need to check whether jupytext is smart enough to check the `pyproject.toml` (might well be, but I haven't checked the docs or tested this before)

It’s a documented configuration option for jupytext: https://jupytext.readthedocs.io/en/latest/config.html
