### ISSUE TITLE
Add an example of how to convert a data frame with lon/lat to a geo data frame

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#214]
r5py requires `geopandas.GeoDataFrame`s as input. It might be that users have, e.g., CSV files with lon/lat locations as input data. While this is not anything that r5py should handle itself, the trivial step to convert a `pandas.DataFrame` with lon/lat columns into a proper geospatial data frame, could be described in the documentation (maybe we can add a page with different ‘tricks’, such as this example, how to set max memory, how to download an OSM protobuffer extract, or how to create a regular grid of whatever kind (s2, h3, ...))

**Comment by wklumpen** [comment]
Could link to this: https://geopandas.org/en/stable/gallery/create_geopandas_from_pandas.html

**Comment by wklumpen** [comment]
I wonder: Can we toss in a handler function that checks whether something is a dataframe, and if it contains a lat/lon or x/y column (similar to how qGIS handles it)?

Could lead to some silent behaviour which isn't expected, but worth discussing.

**Comment by christophfink** [comment]
We already test whether whatever has been passed as an input data set has `id` column (without duplicate values) and a CRS assigned; few things other than a `geopandas.GeoDataFrame` will pass these tests [r5py/util/data_validation.py](https://github.com/r5py/r5py/blob/196ffdf88191a813d0c371b01cb2a344c9948e5d/src/r5py/util/data_validation.py)

**Comment by wklumpen** [comment]
Sounds like we need a FAQ section similar to what Altair has: https://altair-viz.github.io/user_guide/faq.html

**Comment by christophfink** [comment]
> Sounds like we need a FAQ section similar to what Altair has: https://altair-viz.github.io/user_guide/faq.html

Absolutely!

**Comment by christophfink** [comment]
> We already test whether whatever has been passed as an input data set has `id` column (without duplicate values) and a CRS assigned; few things other than a `geopandas.GeoDataFrame` will pass these tests [r5py/util/data_validation.py](https://github.com/r5py/r5py/blob/196ffdf88191a813d0c371b01cb2a344c9948e5d/src/r5py/util/data_validation.py)

Throwing in one more line (`assert isinstance(od_data_set, geopandas.GeoDataFrame)`) would not hurt, either.
