### ISSUE TITLE
Explain how to quick-check a GTFS data set

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#222]
We encountered GTFS data sets of troublesome quality. Let’s add a short checklist to the documentation in which we explain how to:

- use a GTFS validator (e.g., https://github.com/MobilityData/gtfs-validator ) to check technical and syntactical correctness
- explain how to best conduct spot-checks to test for validity of major routes

**Comment by wklumpen** [comment]
Some suggestions:
* Build a "frequency matrix" showing hourly or 15-minue headways  for a given route throughout a sample day and see if there's some issues
* Basic check of total number of routes, total number of trips which can be compared with other similar feeds, similar to the [`route_summary` ](https://gtfs-lite.readthedocs.io/en/latest/gtfs.html#gtfslite.gtfs.GTFS.route_summary) function in GTFS-Lite

I should add these features to an updated [GTFS-Lite](https://github.com/wklumpen/gtfs-lite) package./

**Comment by wklumpen** [comment]
Looking at the MobilityData validator and seeing that it's Java-based, I'm wondering if I might want to put together a Python wrapper for it so that it's more easily runnable with Python.

https://github.com/MobilityData/gtfs-validator

**Comment by wklumpen** [comment]
FWIW I had a pretty easy time running the validator using a `subprocess.call` run of the downloaded JAR file.

**Comment by christophfink** [comment]
https://r5py--238.org.readthedocs.build/en/238/user-guide/user-manual/data-requirements.html#public-transport-schedules-in-gtfs-format

**Comment by christophfink** [comment]
It’s already in the documentation

I would refrain from adding this as a built-in feature, it’s too complex and case-dependent to come up with a universally applicable check (R5 itself parses the file and checks for validity). Input data validation beyond this is the duty of the user (who supposedly is an expert)

(On a side note: let’s try to avoid using `subprocess.call`, there are other ways in 99% of the cases)

**Comment by wklumpen** [comment]
Agreed.
