### ISSUE TITLE
Create a helper function similar to r5r’s `find_snap()`

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#224]
Sometimes, R5 does not manage to properly snap origins or destinations to the network, which results in weird routes or travel times. r5r has a utility function `find_snap()` that ‘simply’ lists all input points, their snapped point and the euclidean distance. This allows the user to then use workarounds, such as assigning the average of neighbouring cells’ travel times to cells with invalid/hugely increased travel times.

cf. https://ipeagit.github.io/r5r/reference/find_snap.html

**Comment by dtreich-itdp** [comment]
I could definitely at least work on a helper function that did deterministic snapping before the O/D matrix was loaded for routing. That would probably just be a few lines with osmnx, though it wouldn't be the most optimized.

**Comment by christophfink** [comment]
That would be very much appreciated! 

I just checked how *r5r*’s helper function works. R5 has the functionality built-in to its `StreetLayer‘ class, simply calling it with two lists of latitudes and longitudes would do the job (plus converting from and to a geodataframe) is all that’s needed.

R5r, here: https://github.com/ipeaGIT/r5r/blob/master/java-r5rcore/src/org/ipea/r5r/SnapFinder.java#L64, calls to `transportNetwork.streetLayer.findSplit()` - in `main`, `r5r.TransportNetwork` already exposes the `street_layer`, so this should be fairly straight-forward.

Until now, we’ve been talking about implementing this as a helper function. However, it might also be smart to add this as a method of the `TransportNetwork` or even as an option (`snap_to_network=False`) to `TravelTimeMatrixComputer.compute_travel_times()`. Also, whether a possible helper function should go to `r5py.util`, or `r5y.r5`, or a new (sub-)module `r5py.helpers` (or similar) has not been discussed. 

Feel free to implement it as you see fit! Can also be a minimal implementation from which we can take it further at a later point in time.

Thanks a lot!

**Comment by christophfink** [comment]
See our contributing guide lines at: https://github.com/r5py/r5py/blob/main/docs/CONTRIBUTING.md
