### ISSUE TITLE
Add badges/shields showing the number of downloads

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#228]
(as discussed in our meeting, yesterday)

**Comment by christophfink** [comment]
So I did not find a quick way of generating one badge showing the downloads from both repositories, so I now added separate badges for each; and - well - it’s getting crowded in our README. 

Can you all please checkout https://github.com/christophfink/r5py/tree/228-downloads and then reply back here whether you feel this is already too much (it is for me, to be honest, but I’m fine with any decision we make) @HTenkanen @wklumpen @rafapereirabr

**Comment by christophfink** [comment]
Follow-up question: should we remove the row of version badges (Python 2 does not exist anymore; of course, we have the latest version on pipy and conda)

**Comment by christophfink** [comment]
The longer I play around with it, the less I like any of the badges 😂 🤯
I’ll prepare a couple of different versions, including moving some of the badges to the bottom of the page, but probably only over the weekend.

**Comment by wklumpen** [comment]
So I don't think it's too cluttered (actually lines up nicely with the logo on the right), but I do agree with @christophfink that perhaps we don't need the version badges.

I don't feel too strongly about it either way, but I don't think it's a clutter issue.

**Comment by rafapereirabr** [comment]
I agree it's not too cluttered. If you really feel like reducing the number of badges, I would remove the `python 3`. I would also replace the `Anaconda 0.0.4` and `PyPi 0.0.4 ` badges by a single badge `Version 0.0.4`, specially because we already mention in the Installation section that the package can be installed use mamba, pip or conda.

**Comment by christophfink** [comment]
I played around with the badges a bit (shuffled the order), and followed Rafa’s suggestion to have one version badge, only. See PR #232
