### ISSUE TITLE
OpenJDK link in documentation is broken

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#231]
I get a 404 error following this link to OpenJDK 11 in the docs: https://openjdk.org/java-se-ri/11

Seems now we might need to point people to the OpenJDK Archive: https://jdk.java.net/archive/

**Comment by christophfink** [comment]
https://openjdk.org/projects/jdk/11/ works, too. Is there some place that explains the different options (e.g., the Microsoft supplied OpenJDK binaries for Windows)?

**Comment by wklumpen** [comment]
Not that I know of?
