### ISSUE TITLE
Data for Seoul. South Korea 

### ISSUE THREAD

**Issue by cdkang** [r5py/r5py#241]
Hello, 
I deeply appreciate your sharing r5py. 

Now I am wondering how to get data for Seoul, South Korea. 

Sincerely,

**Comment by christophfink** [comment]
Hi @cdkang!

We are in the middle of revamping r5py’s documentation, which will also include a chapter on where to obtain data from. 

For the street network, you can use OpenStreetMap dumps (in pbf format), which you can download, e.g., from <https://geofabrik.de> or <https://download.bbbike.org/osm/bbbike/>, or using a library such as <https://pyrosm.readthedocs.org>. 

GTFS data is often available from the open data portals of cities or transport providers. Many data sets are also collected on <https://transit.land>, but I’ve not found any Korean data set there. I also quickly checked Seoul’s open data portal, <https://data.seoul.go.kr>, but for lack of speaking the language I was not able to search properly. A good starting point is usually also the local/regional transport authority, we’ve also heard of GTFS data sets being made available only after polite e-mail contact (the data most likely exists to start with).

I hope this helps, good luck with obtaining a usable data set! :)

(see also <https://r5py.readthedocs.io/en/stable/notebooks/basic-usage.html#where-to-get-these-datasets>)

**Comment by cdkang** [comment]
Hello, 

I appreciate your information. 

Sincerely,
