### ISSUE TITLE
MacOS: process died unexpectedly

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#243]
So we have this really weird situation since the new year that one of the many test runs fails. It’s always one of the MacOS jobs (with system-wide Java environment), the error is always connected to the JVM not finding libjsig, and **re-running the failed jobs from the web-UI always fixes the issue**.

This must be some kind of GitHub actions bug. I checked that the dependencies have not been updated since it last worked without problems. 

Not sure whether we can do anything about this, or whether we should sit it out. 

---
**EDIT**

It seems this does not only occur on the GitHub CI/CD runners, but also on bare-metal MacOS, see https://github.com/r5py/r5py/issues/254#issuecomment-1433401053 

Very likely, this is connected to dyld not being able to locate `libjsig.so` on some MacOS/JVM combinations.

**Comment by christophfink** [comment]
This seems to have resolved, jobs pass on first try these days

**Comment by christophfink** [comment]
Seems this is not over :-/ very weird ...

**Comment by christophfink** [comment]
I’m now trying to actually find `libjsig.so`, rather than guessing where it should be. This could be all that’s needed to resolve this issue

**Comment by christophfink** [comment]
@ethan-moss Could you check whether the changes in pull request #267 solve the issue? 
To install r5py from the pull request, run:

```
pip install git+https://github.com/r5py/r5py.git@refs/pull/267/head
```

Thanks so much for your help!

**Comment by ethan-moss** [comment]
Hey @christophfink - thanks for looking into this. Good news, It looks like this has been resolved! With the help of someone else, we tried a few different GTFS/PBF sources:

- The 'resource tracker unexpectedly ended' warning was not seen at all. Ran several repeats of the same config to confirm this too, and never saw this warning. Re-running these with an older`r5py` version does yield the warning in all cases-> good sign this fix is working. 
    - Side note: the 'illegal reflective access operation has occurred' warning still remains, but I suspect this is an unrelated issue. It appears the first time the `TransportNetwork` is built, but for subsequent rebuilds this warning does not appear (with the same python kernel).  
- Results were deterministic and identical to runs using the `r5py` version in the main branch.
- Also tested on two machines running macOS and different silicon, 1 ARM and 1 intel - this warning was not seen at all on both.

Hope this helps! What was the cause of this warning in the end?

**Comment by christophfink** [comment]
Fantastic, thank you!

> What was the cause of this warning in the end?

Two things that were intertwined: first, I missed that Java libraries have a different extension on MacOS than on Linux, and second, I made r5py guess the location of the signal handling pre-load library, instead of actually finding it. Fixing the do made the issue go away

**Comment by christophfink** [comment]
> Side note: the 'illegal reflective access operation has occurred' warning still remains, but I suspect this is an unrelated issue. It appears the first time the TransportNetwork is built, but for subsequent rebuilds this warning does not appear (with the same python kernel).

Yes, this, indeed, is an upstream issue. Conveyal would have to exchange the mapdb library to a newer version (the one they are using is almost a decade old), but I guess they have good reasons to stick to the older version

I haven’t found a way of masking the output, which would be our best chance at hiding the warning message that we cannot do anything about
