### ISSUE TITLE
Recreate r5r Vignette

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#25]
Building off of r5r's [introductory vignette](https://ipeagit.github.io/r5r/articles/intro_to_r5r.html), I am proposing we use the follow syntax/workflow as part of a larger wrapping functuion.

For now this sits as a sort of "style" guide but eventually I will create a separate issue to write a wrapper.

```python
# Installation with pip install r5py
import os
from datetime import datetime

from r5py import r5Analysis, TransportNetwork, get_r5  # Names TBD

import pandas as pd

data_path = os.path.join("extdata", "poa") # Must contain a pbf, might contain a ZIPped GTFS
osm_pbf = "testdata.pbf"
gtfs = ["testgtfs.zip"]


# To "setup" r5 we pull the JAR file and store it in the local package directory
# This should only need to be done once per installation, or when a new version is needed
# Will place r5 JAR in the appropriate temp folder depending on OS
get_r5()

# Create a reuseable transportation network
network = TransportNetwork(osm_pbf=osm_pbf, gtfs=gtfs)

# Create an instance of the analysis class with the appropriate data folders
# We could provide a few different class functions to get people up and running
# We could easily wrap the above transport network step in utility functions in the r5Analysis class
r = r5Analysis(network=network, verbose=False)


# Load up the data
poi = pd.read_csv(os.path.join(data_path, "poa_points_of_interest.csv")
points = pd.read_csv(os.path.join(data_path, "poa_hexgrid.csv").sample(10, replace=True) 


# Travel time matrices
mode = ["WALK", "TRANSIT"]
max_walk_dist = 5000
max_trip_duration = 120
departure_datetime = datetime(2019, 5, 13, 14, 0, 0, 0) # Currently in timezone naive time

# Generate Travel Time Matrix
ttm = r.travel_time_matrix(
    origins=points,
    destinations=points,
    mode=mode,
    departure_datetime=departure_datetime,
    max_walk_dist=max_walk_dist,
    max_trip_duration=max_trip_duration,
    verbose=False)
    
# Detailed itineraries
origins = poi.iloc[10,]
destinations = poi.iloc[12,]
max_walk_dist = 10000

# Get some itineraries
dit = r.detailed_itineraries(
    origins=origins,
    destinations=destinations,
    mode=mode,
    departure_datetime=departure_datetime,
    max_walk_dist=max_walk_dist,
    shortest_path=False,
    verbose=False)

# Grab a street network
street_net = r.street_network_to_sf()
```

**Comment by wklumpen** [comment]
Somewhere in here we need to allow the user to set the Java parameters. This is where a context manager or larger handler class might come in handy. But it can be passed to individual networks also:

```python
TransportNetwork(java_params=['-Xmx2G'])
```

**Comment by christophfink** [comment]
> ```
> # To "setup" r5 we pull the JAR file and store it in the local package directory
> # This should only need to be done once per installation, or when a new version is needed
> # Will place r5 JAR in the appropriate temp folder depending on OS
> get_r5()
> ```
> 
> I think this is an unnecessary step? At the moment, the r5py does this automatically (I believe), and I'm not sure whether this is something that the user should need to do manually?
> 
> I see the point in following similar style as in r5r, but wouldn't it actually make more sense to try to automate this step in r5r as well? Or is there something specific to R that does not allow doing it..I remember @rafapereirabr mentioned something about this during our call.

Yeah, I’m also not sure, whether there was more reason to download the JAR then (maybe to allow for extra checks?).

**Comment by HTenkanen** [comment]
Also from the vignette, would it make more sense to name `r5Analysis` just as `Analysis`? As the package name contains r5, I find it perhaps a bit tautonomic to repeat the r5 with the class/function names, what do you thing?

**Comment by christophfink** [comment]
> You can set the max java memory as a parameter to whatever CLI exec we build, and/or in the config file. It’s using configargparse, have to check how to set parameters from within a script.

This is maybe a case of premature optimisation, it’s in here: https://github.com/r5py/r5py/blob/main/src/r5py/util/memory_footprint.py

**Comment by christophfink** [comment]
> Also from the vignette, would it make more sense to name `r5Analysis` just as `Analysis`? As the package name contains r5, I find it perhaps a bit tautonomic to repeat the r5 with the class/function names, what do you think?

Not sure whether we need such an umbrella class here, at all? that’s a bit like what a module should be in python, isn’t it?
I thought the functional interface (wrappers around the object-based one) could be exposed directly in the package root, so as `r5py.travel_time_matrix()`, or so.

**Comment by HTenkanen** [comment]
> > Also from the vignette, would it make more sense to name `r5Analysis` just as `Analysis`? As the package name contains r5, I find it perhaps a bit tautonomic to repeat the r5 with the class/function names, what do you think?
> 
> Not sure whether we need such an umbrella class here, at all? that’s a bit like what a module should be in python, isn’t it? I thought the functional interface (wrappers around the object-based one) could be exposed directly in the package root, so as `r5py.travel_time_matrix()`, or so.

Yep, this is how I would do it (and how I have done it e.g. with [pyrosm](https://pyrosm.readthedocs.io/en/latest/basics.html)), but I guess this is also a bit of a question how closely we want to couple the user interface with r5r. 🤔

**Comment by HTenkanen** [comment]
I guess we need to discuss a bit more about the API design, because Python and R are just used quite differently and we need to balance between doing things how they feel natural for Python and how closely the r5r and r5py user interfaces are to each other.

**Comment by christophfink** [comment]
> > Also from the vignette, would it make more sense to name `r5Analysis` just as `Analysis`? As the package name contains r5, I find it perhaps a bit tautonomic to repeat the r5 with the class/function names, what do you think?
> 
> Not sure whether we need such an umbrella class here, at all? that’s a bit like what a module should be in python, isn’t it? I thought the functional interface (wrappers around the object-based one) could be exposed directly in the package root, so as `r5py.travel_time_matrix()`, or so.

And these functions could go straight into the same files as the wrapped classes to make it a bit more organised, and can then be imported in the top level `__init__`:

for instance, for the travel time matrix, adding something like that to `src/r5py/r5/travel_time_matrix.py`:

```
class TravelTimeMatrix: 
... # class content (is already there)


def travel_time_matrix(arg, arg, arg):
    ttm = TravelTimeMatrix(arg, arg, arg)
    return ttm.compute_travel_times()

```

And then in `src/r5py/__init__.py`:

```
__all__ = [
    ...
    "travel_time_matrix",
    "TravelTimeMatrix"
]

from r5.travel_time_matrix import TravelTimeMatrix, travel_time_matrix
```

**Comment by rafapereirabr** [comment]
Hi all. I like to see how the workflow of the vignette raises somes issues about the API design and user interface. Having said that, I have the impression there are multiple issues being discussed above. Perhaps we should treat them separately in different issues, whenever possible. Here are a few points that could be addressed as separate issues:

1. Seeting memory
Setting Java memory `TransportNetwork(java_params=['-Xmx2G'])`.  What's the best approach to allows users allocate emory to Java? In `r5r`, users need to set one time this at the start of the R session, before loading the r5r library. I believe there should be better ways to do this in Python.

2. Downloading R5 with `get_r5()`
In `r5r` we have the an equivalent `download_r5()` fuction that downloads R5 once per installation. In our case, `download_r5()` can be called by users. However, because we want to reduce the number of steps between installing the package and analyzing the data, the user only needs to run the `setup_r5()` and the function will automatically run `download_r5()`. In practice, `setup_r5()` is the first function that the user needs to call, and the user only needs to call 2 functions: `setup_r5()`  plus a routing/accessibility funcion.

3. Building the network
I believe `TransportNetwork()` and `setup_r5()` would be the equivalent function used to create a network, right?
- r5py: `network = TransportNetwork(osm_pbf=osm_pbf, gtfs=gtfs)`
- r5r: `network =  setup_r5( data_path = "local_dir")`

I see that users would need to pass the the addresses of a `osm.pbf` and `gtfs.zip` files to `TransportNetwork()`. I find this behavior a bit strange. How does it work when users have two or more GTFS feeds from different agencies. We know R5 automatically detects and takes in one `osm.pbf` and all the `gtfs.zip` files in the path. This one of the reasons we require `r5r` users to input the address of the local directory where the data is stored. Perhaps we should have a separate issue to discuss the workflow we would expect from users and the expected behavior of these download and build network functions.


5. Creating an instance of the analysis class with the appropriate data folders: `r5Analysis`
I agree with @christophfink , it would be best to exposed directly in the package root as `r5py.travel_time_matrix()`. This way, we reduce the number of steps users need to take.

**Comment by christophfink** [comment]
> 2\. Downloading R5 with `get_r5()`
>         In `r5r` we have the an equivalent `download_r5()` fuction that downloads R5 once per installation. In our case, `download_r5()` can be called by users. However, because we want to reduce the number of steps between installing the package and analyzing the data, the user only needs to run the `setup_r5()` and the function will automatically run `download_r5()`. In practice, `setup_r5()` is the first function that the user needs to call, and the user only needs to call 2 functions: `setup_r5()`  plus a routing/accessibility funcion.

This is not really visible to the user, and does not require interaction. Not sure whether we should force an extra step here. Simply importing `r5py` does the job.

**Comment by christophfink** [comment]
On a more general note, what exactly are we talking about in this issue:

1. streamlining the ’basic usage’ notebook to be more closely aligned with r5r`s vignette, or
2. adding a minimal example (that aligns well with r5r’s vignette) to the README.md?

**Comment by rafapereirabr** [comment]
> > 2. Downloading R5 with `get_r5()`
> > In `r5r` we have the an equivalent `download_r5()` fuction that downloads R5 once per installation. In our case, `download_r5()` can be called by users. However, because we want to reduce the number of steps between installing the package and analyzing the data, the user only needs to run the `setup_r5()` and the function will automatically run `download_r5()`. In practice, `setup_r5()` is the first function that the user needs to call, and the user only needs to call 2 functions: `setup_r5()`  plus a routing/accessibility funcion.
> 
> This is not really visible to the user, and does not require interaction. Not sure whether we should force an extra step here. Simply importing `r5py` does the job.

Oh, so r5py calls `get_r5()` once the user imports the library. I'm sorry I missed this. Thanks for clarifying !

**Comment by wklumpen** [comment]
Given that #80 covers @christophfink 

> On a more general note, what exactly are we talking about in this issue:
> 
> 1. streamlining the ’basic usage’ notebook to be more closely aligned with r5r`s vignette, or
> 2. adding a minimal example (that aligns well with r5r’s vignette) to the README.md?

Given that #80 covers the first item and #86 covers the API discussion a bit I'm suggesting we close this off for now.
