### ISSUE TITLE
ValueError when breakdown=True

### ISSUE THREAD

**Issue by zehbrandao** [r5py/r5py#255]
Hi,

I'm not managing to get the detailed breakdown of the routing results. I've already tried it out with two different datasets — one being the [Helsinki dataset](https://github.com/r5py/r5py/tree/main/docs/data/Helsinki) from R5py's repo — but every time I get a ValueError. A section of the traceback is attached below.

```
File ~\anaconda3\envs\pyGeo\lib\site-packages\r5py\r5\travel_time_matrix_computer.py:207, in TravelTimeMatrixComputer._parse_results_of_one_origin_details(self, from_id, results)
    196 for ((column_name, column_type), column_data) in zip(
    197     DATA_COLUMNS.items(), zip(*details)  # transpose data
    198 ):

    [...]

    203     # fortunately, we get str, which remains a character string when
    204     # cast to dtype('O')
    206     if isinstance(column_type, pandas.SparseDtype):
    207         column_data = [
    208             [
--> 209                 column_type.subtype.type(value)  # cast
    210                 for value in row.split("|")
    211             ]
    212             if row is not None
    213             else []
    214             for row in column_data
    215         ]
    216     else:
    217         column_data = [
    218             column_type(row) if row is not None else None  # cast
    219             for row in column_data
    220         ]

    [...]

    ValueError: could not convert string to float: '6,0'

```

> **Environment:**
>  - OS: Windows 11 22h2
>  - Package source: conda-forge
>  - Python 3.9.16

All the other examples in the documentation seem to work alright, although there are occasional slight variations in the computed times, but these are probably due to the behaviour described in #240.

It does look like something silly: the decimal separator in the string, I'd say. But I'm not quite sure how to go about it, though: if the problem is on my end, I'm failing to see what's causing it; if it's on your end, I'm not (yet) familiar with the pull request process.

**Comment by christophfink** [comment]
Thanks for reporting this, and I’m almost certain you’re correct when you write

> It does look like something silly: the decimal separator in the string, I'd say. But I'm not quite sure how to go about it, though: if the problem is on my end, I'm failing to see what's causing it; if it's on your end, I'm not (yet) familiar with the pull request process.

I’ll look into this, and (not wanting to jinx it, but) believe this will be an easy fix

**Comment by christophfink** [comment]
Just to confirm, could you answer the following questions, still? Thanks

- Which language is your Windows installation running on?
- Could you share the output of
  ```
  import python
  print(locale.localeconv()
  ```

Thanks!

**Comment by zehbrandao** [comment]
Hello!

Well, it's set to Portuguese(BR) — although it's originally a laptop with US keyboard.

 As for the output:

> {'int_curr_symbol': '',
>  'currency_symbol': '',
>  'mon_decimal_point': '',
>  'mon_thousands_sep': '',
>  'mon_grouping': [],
>  'positive_sign': '',
>  'negative_sign': '',
>  'int_frac_digits': 127,
>  'frac_digits': 127,
>  'p_cs_precedes': 127,
>  'p_sep_by_space': 127,
>  'n_cs_precedes': 127,
>  'n_sep_by_space': 127,
>  'p_sign_posn': 127,
>  'n_sign_posn': 127,
>  'decimal_point': '.',
>  'thousands_sep': '',
>  'grouping': []}

**Comment by christophfink** [comment]
Thanks!

Could you install the r5py version from pull request #256 and try whether you still are seeing the same error?

Inside your conda environment, run the following steps to install the pull request version (to be on the safe side, you could also create a new conda environment, first):

```
conda install pip git
pip install git+https://github.com/r5py/r5py.git@refs/pull/256/head
```

(compare https://pip.pypa.io/en/stable/topics/vcs-support/#git)

**Comment by zehbrandao** [comment]
Hi, @christophfink!

First of all, thank you for the quick repsonses!

Second, well... I've created a new environment in which I've installed only the pull request version, as you instructed and jupyter lab. It doesn't throw an error anymore, BUT the breakdown doesn't work: r5py always displays the aggregate result, irrespective of how the breakdown parameter is set.

**Comment by christophfink** [comment]
> BUT the breakdown doesn't work:
Oh that’s indeed true! I forgot about other updates and (breaking) changes that happened in-between. In line with r5r’s API, we moved detailed breakdowns into a separate class. Please use `r5py.DetailedItinerariesComputer` in place of `TravelTimeMatrixComputer(..., breakdown=True)`. 

The documentation for this is not yet finished, but you can check the draft documentation here: https://r5py--238.org.readthedocs.build/en/238/user-guide/user-manual/detailed-itineraries.html

**Comment by christophfink** [comment]
If you would find the time, it would be great if you could check whether the original issue has been resolved when using the `DetailedItinerariesComputer` and report back here. Thank you so much!

**Comment by zehbrandao** [comment]
Hello, there!

Sorry about the late response. I took a few days off of anything work related. The beakdown seems to have worked now. I have not tried it with my dataset (yet) nor have I (yet) performed any detailed checks on the results, but it looks alright and no exceptions thrown.

Thank you so much! :)

**Comment by christophfink** [comment]
Fantastic that it works! Thanks for the bug report!
