### ISSUE TITLE
"NaN" output when attempting to find travel time 

### ISSUE THREAD

**Issue by emfikre** [r5py/r5py#270]
** Description of issue**
We are trying to replicate the usage example in the documentation to compute travel times in Calgary. We have been able to load the transport network using all open data and have created a grid of points covering the area of interest using the fishnet feature in ArcGIS and have also tried the grid function QGIS.

When using the travel time matrix computer. We are currently getting "NaN" as our result for travel times.

We were able to get travel times using the data for the usage example in Helsinki.

**Data that we've used**
A google drive link containing all the data and the jupyter notebook that we've used can be found here. All data was open data.
[https://drive.google.com/drive/folders/10rP10nfqTPKaMNSQVqgYoBrPRBiT8a_P?usp=sharing](url)

**Code**
```
import sys
sys.argv.append(["--max-memory", "5G"])
```
```
import geopandas 
import numpy as np

points_url = "../fishyIII.gpkg"
points = geopandas.read_file(points_url)
points['geometry']= points['geometry'].centroid
points = points.rename(columns={'Id': 'id'})
points.head()
```
![image](https://user-images.githubusercontent.com/64706891/224588712-dd440ffc-7db8-4d8c-91d6-eeffd552fd69.png)

```
import matplotlib
points.explore(cmap="Blue", marker_type = "circle_marker", marker_kwds={"radius": 12})
```
![image](https://user-images.githubusercontent.com/64706891/224588293-028dca16-3c48-45d3-a4c7-cce9b2fb70d9.png)

```
# Allow 8 GB of memory
import sys
sys.argv.append(["--max-memory", "8G"])
```
```
from r5py import TransportNetwork

transport_network = TransportNetwork(
    "C:/Users/emfik/OneDrive/Documents/4th Year/ENCI 570/Latest Try/calga.osm.pbf",
    [
        "C:/Users/emfik/OneDrive/Documents/4th Year/ENCI 570/CT_GTFS.zip"
    ]
)
```

```
origin = points.loc[points["id"] == 5].copy()
origin.explore(color="blue", max_zoom=14, marker_kwds={"radius": 12})
```
![image](https://user-images.githubusercontent.com/64706891/224588957-b2748c67-45b7-4521-b798-552b6716bf6b.png)
```
import datetime
from r5py import TravelTimeMatrixComputer, TransitMode, LegMode


travel_time_matrix_computer = TravelTimeMatrixComputer(
    transport_network,
    origins=origin,
    destinations=points,
    departure=datetime.datetime(2023,2,3,8,0),
    transport_modes=[TransitMode.TRANSIT, LegMode.WALK]
)
```
```
travel_time_matrix = travel_time_matrix_computer.compute_travel_times()
travel_time_matrix
```
![image](https://user-images.githubusercontent.com/64706891/224589098-68e52511-123d-4283-acac-803bd27a4bb1.png)

**Comment by christophfink** [comment]
Thanks for reporting this issue. 

For the current version, input points should be in `EPSG:4326` (WGS84). 

In the upcoming version, rp5y transparently transforms geodata on-the-fly (compare #192 )

**Comment by congying-hu** [comment]
I came across the same issue! Thanks for your reporting that I could figured out what's happening!
