### ISSUE TITLE
Clean up R5’s many temporary files

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#274]
R5 leaves behind quite many temp files, e.g., `/tmp/GeoTools/*` and `/tmp/com.conveyal.gtfs.*.db`. We need some mechanism to clean them up, as they add up over time (e.g., just after running the normal test suite, they amount to almost 800MiB)

**Comment by christophfink** [comment]
A clean approach would be to have R5 put all temp files into a particular directory, that we can remove after the fact. See https://stackoverflow.com/a/1924159 for how to set the Java interpreter’s default temp dir

**Comment by christophfink** [comment]
the `com.conveyal.gtfs.*.db` files are created here: https://github.com/conveyal/r5/blob/f2d7c32288390f37a6144f4a1b91c0e57a6d6c21/src/main/java/com/conveyal/gtfs/GTFSFeed.java#L890

**Comment by christophfink** [comment]
The `GeoTools` directory is from here: https://docs.geotools.org/stable/userguide/library/referencing/hsql.html

**Comment by rafapereirabr** [comment]
@mvpsaraiva , is this something that r5r could also use?
