### ISSUE TITLE
Add option to `DetailedItineraries()` to retain geometry 

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#278]
R5r’s `detailed_itineraries` can return the geometry of the travelled path. Let’s implement this in r5py, too

**Comment by christophfink** [comment]
In general, r5r handels the `DetailedItineraries` a lot different than r5py: rather than using R5’s summarising functions, r5r loops locally across all possible combinations or permutations. See https://github.com/ipeaGIT/r5r/blob/346356ead791e3a4e5bc49a3e54b6bb61f32888a/java-r5rcore/src/org/ipea/r5r/Process/DetailedItineraryPlanner.java

**Comment by wklumpen** [comment]
What's the best approach for us?
