### ISSUE TITLE
Detailed Itineraries Computer returns multiple records for same OD pair

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#280]
Running the detailed itineraries computer returns multiple rows for the same OD pair, some of which have no variations in the routes used. Some documentation might be needed to clarify how to interpret (and handle) this output.

Image below:

![image](https://user-images.githubusercontent.com/7478016/230166807-705ca61a-143b-4624-97f2-d3ab496d9bd8.png)

**Comment by christophfink** [comment]
Would you have the motivation to look into how R5 comes up with these, how r5r handles ‘duplicate’ rows, and what would be the best way to go forward?

Concerning documentation, there is this long-time half-finished PR #238 in which I am attempting a major reorganisation of the documentation, but which - for lack of time to write new parts - is not yet finished. Please merge #238 into a potential new PR to continue work using the new structure

**Comment by christophfink** [comment]
See also the (preview) of the changes to the documentation here: https://r5py--238.org.readthedocs.build/en/238/

**Comment by christophfink** [comment]
BTW, I would assume that these (identical, for us) rows are for the same connection at different times during `departure_time_window`, so it’s just that some information is missing here for us: the rows are most likely not identical if considering departure time

**Comment by wklumpen** [comment]
Agreed I feel like this has to be the result of a different itinerary somewhere (@mvpsaraiva or @rafapereirabr might have thoughts) but where outside of routes/stops I cannot figure out (my guess is at the trip_id level).

In any case it would be good to have some advice on how to aggregate these if you say wanted a "median wait time" or "median ride time"

**Comment by rafapereirabr** [comment]
I agree with @christophfink . Perhaps the simple solution here would be to add a column to the output indicating the departure time.

**Comment by christophfink** [comment]
This turns out to be a bigger fish to fry that I anticipated, will need a few days to model r5py’s `DetailedItinerariesComputer` after r5r’s (currently hitting semi-obscure Java errors)
