### ISSUE TITLE
Detailed Itineraries Computer does not accept all listed kwargs

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#281]
The `DetailedItinerariesComputer`'s current documentation suggests kwargs accepted are:

```            
**kwargs : mixed
    Any arguments than can be passed to r5py.RegionalTask:
    ``departure``, ``departure_time_window``, ``percentiles``, ``transport_modes``,
    ``access_modes``, ``egress_modes``, ``max_time``, ``max_time_walking``,
    ``max_time_cycling``, ``max_time_driving``, ``speed_cycling``, ``speed_walking``,
    ``max_public_transport_rides``, ``max_bicycle_traffic_stress``
```

However `percentiles` in this case does nothing (passing percentiles doesn't affect the computation and output). 

I'm wondering if we should include some additional language, warning, or output when kwargs are used here that don't actually do anything.

**Comment by christophfink** [comment]
Yes that’s true, it, indeed, does not change the results. This is connected to #278 (which requires a major overhaul on the `DetailedItineraries`), I’ll assign this to myself and address both issues together

**Comment by wklumpen** [comment]
@christophfink We can probably close this?

**Comment by christophfink** [comment]
Let’s rather add it to the documentation PR and milestone
