### ISSUE TITLE
Should r5py clean up the `mapdb` and `mapdb.p` files after running?

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#287]
R5 creates `.mapdb` and `.mapdb.p` files from the OSM PBF file when it runs. Should these be cleaned up after running? They're quite large. Should only be cleaned up on deconstruction of the TransportNetwork object though.

**Comment by christophfink** [comment]
It should clean these files, since PR #275 . In fact, r5py symlinks or copies the input files into a temporary directory, which it cleans upon exiting. There should not be any `.mapdb`/`.mapdb.p` files created, even. 

Can you remove them manually, and try whether they are recreated?

**Comment by wklumpen** [comment]
I will make sure I've got the most updated version and check again, hopefully sometime this week or next.

**Comment by wklumpen** [comment]
Confirmed - my issue was that I wasn't updated to the latest head version.
