### ISSUE TITLE
Java Error when running in a `flask-executor` thread

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#300]
This is more of a troubleshooting issue that it may actually be an R5py thing, and it's possible that the current PRs might address this, but I'm recording it here for posterity.

I'm using [`flask-executor`](https://flask-executor.readthedocs.io/en/latest/) to execute a run of R5py. I have confirmed that R5py runs successfully under the same data/configuration outside of the thread, but while building the analysis network via the tread I captured the following error:

```
java.lang.RuntimeException: Error occurred while parsing OSM file /tmp/r5py3wrx6q9c/TransportNetwork_7f86906b33a0/osm.pbf
```

I wonder if this is a configuration setting issue that has to do with threads/available resources. I have also confirmed that I'm using ``flask_executor`` correctly as I am able to run a different JAR program (MobilityData validator) without any issues in a thread.

Any thoughts would be appreciated!

**Comment by wklumpen** [comment]
Assigning myself to try it with the updated head after all the PRs.

**Comment by christophfink** [comment]
So this is definitely related to the ‘working copy’ of the input files that `r5py.TransportNetwork` tries to create, see, e.g., https://github.com/r5py/r5py/blob/a2ca3e757663c0ca336162faaeb93986fa3bb76d/src/r5py/r5/transport_network.py#L216 

Not sure whether the `TransportNetwork._cache_directory` is not created properly, whether something goes wrong when the input file is copied or linked there, or whether there is a race condition with identical temp file names

**Comment by wklumpen** [comment]
> So this is definitely related to the ‘working copy’ of the input files that `r5py.TransportNetwork` tries to create, see, e.g.,
> 
> https://github.com/r5py/r5py/blob/a2ca3e757663c0ca336162faaeb93986fa3bb76d/src/r5py/r5/transport_network.py#L216
> 
> Not sure whether the `TransportNetwork._cache_directory` is not created properly, whether something goes wrong when the input file is copied or linked there, or whether there is a race condition with identical temp file names, but those are my first guesses

Recognizing this is wading into the troubleshooting code realm, what's the possible approach here? While I'm submitting code in a thread (as it's being instantiated by a web application), I'm not at the moment doing any simultaneous execution of threads, so I don't know about a race condition issue.

I'm also now seeing on the larger stack trace an eventual `ClassNotFoundException` which may be a classpath issue. Let me get an updated version of R5py going and see if that resolves the issue.

**Comment by wklumpen** [comment]
Update: Running a separate python script with the same code in it and using `os.subprocess.POpen` seems to work. So there's clearly a threading thing going on somewhere.

Not sure what to do with this issue aside from closing it as wontfix?

**Comment by JackTatt** [comment]
Hello,
I'm not sure if this error is related to or not related to the above issues @wklumpen. 
I have a pandas dataframe of pairs of coordinates (saved as tuples) I need to find travel time (by walking) between.
I use the following code to setup and run r5py:
`transport_network = r5py.TransportNetwork(
        'GTHA_OSM20230525.osm.pbf',
        'GO-GTFS2023MAY4.zip')
    ttmatrix = r5py.TravelTimeMatrixComputer(transport_network,
                                             origins=interchanges['from_loc'],
                                             destinations=interchanges['to_loc'],
                                             transport_modes=r5py.LegMode.WALK)
    interchanges.minCT = ttmatrix.compute_travel_times()
`
Running the above gets the following error: **java.lang.IndexOutOfBoundsException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 810721**

Full traceback below:
`Traceback (most recent call last):

  File TransportNetwork.java:131 in com.conveyal.r5.transit.TransportNetwork.fromFiles

Exception: Java Exception


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File C:\ProgramData\Anaconda3\envs\civ-1599\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\jack tattersall\documents\masc\thesis\data analysis\connectionpunctuality\connex_functions.py:135
    transport_network = r5py.TransportNetwork(

  File C:\ProgramData\Anaconda3\envs\civ-1599\lib\site-packages\r5py\r5\transport_network.py:48 in __init__
    self._transport_network = com.conveyal.r5.transit.TransportNetwork.fromFiles(

java.lang.IndexOutOfBoundsException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 810721
`
Checking the traceback, I note that the Traceback is referencing code from r5py and not my own code (which is in a file called connex_functions.py).
I appreciate any advice or assistance.
Thank you.

**Comment by wklumpen** [comment]
Hi Jack,

This is likely the same issue as #277 which seems to have popped up occasionally. It is likely to do with some missing or incomplete data in the OpenStreetMap PBF file you are using.

My suggestion is to head over to [BBBike](https://extract.bbbike.org/) and use their "bounding box" tool (you can make a non-square extract) to extract a PBF file (choose the PBF format in the top left) that's fresh and updated. The resulting export has worked consistently for me.

**Comment by christophfink** [comment]
@wklumpen since you added the ‘wont fix’ label - should we close this issue?
