### ISSUE TITLE
Is the `src` layout too uncommon for new contributors?

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#31]
I think it is not very typical in Python packages to include a `src` directory (now we have `src/r5py`). I.e. typically you would just have a folder with the name of your library, i.e. in our case `r5py`. I know `src` etc. is very common in Java packages etc. but perhaps we don't need it?

**Comment by christophfink** [comment]
Using a src directory is the recommended structure: https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by HTenkanen** [comment]
Ha, interesting, didn't know about this recommendation 🤔 Here are some reasons why it seems to be recommended (not very significant reasons, imo) :
https://py-pkgs.org/04-package-structure.html#the-source-layout

It's interesting that this is the recommendation because it's not followed often.. Eg none of the "big libraries" seem to follow this practice (scipy, pandas, geopandas, numpy, sklearn, tensorflow, etc. Only checked these). I wonder why there seems to be clear disagreement here with the community. 🤔

Again, happy to keep it like this, but seems to differ from how things are typically done in the ecosystem.

**Comment by HTenkanen** [comment]
Fair enough. 👍🏻 I'm okay keeping the structure as it is, and follow the src structure, although it feels a bit weird (old habits..)
