### ISSUE TITLE
Warn if `origins.equals(destinations)` in `DetailedItinerariesComputer.__init__()` (same-to-same routes)

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#312]
**Describe the bug**
As titled, the `DetailedItinerariesComputer` appears to not compute segments/travel times for a Calgary example, when `TravelTimeMatrixComputer` produces realistic results.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the attached zip data
2. Run the included Python workbook using an environment

**Expected behaviour**
A detailed itineraries list that mimics the travel time matrix produced via the `TravelTimeMatrixComputer`

**Environment:**
 - OS: Ubuntu 22.04.2 LTS
[Expanded Matrix Example.pdf](https://github.com/r5py/r5py/files/12314835/Expanded.Matrix.Example.pdf)
[calgary_data.zip](https://github.com/r5py/r5py/files/12314894/calgary_data.zip)

**Comment by wklumpen** [comment]
Also the matrix that's returned seems to include `r5py` enums like `TransportMode.WALK` and timedeltas; something we may want to consider converting as an output (it also produces a `DataFrame` not a `GeoDataFrame`). Can open as separate issues if this is something we want to discuss.

**Comment by wklumpen** [comment]
More digging: The `LINESTRING` produced is of zero length, e.g.

```
LINESTRING (-114.11664088946674 51.111660511582606, -114.11664088946674 51.111660511582606)
```

**Comment by christophfink** [comment]
> Also the matrix that's returned seems to include `r5py` enums like `TransportMode.WALK` and timedeltas; something we may want to consider converting as an output (it also produces a `DataFrame` not a `GeoDataFrame`). Can open as separate issues if this is something we want to discuss.

I’m on board with returning GeoDataFrames (ran into that myself just yesterday), but I would like to keep the properly typed transport modes and timedeltas, they allow so much more than a plain string or numeric value (e.g. `TransportMode.is_transit_mode`, proper comparison, arithmetic with dates/times, ...)

**Comment by christophfink** [comment]
> More digging: The `LINESTRING` produced is of zero length, e.g.
> 
> ```
> LINESTRING (-114.11664088946674 51.111660511582606, -114.11664088946674 51.111660511582606)
> ```

I know what you’re running into (or I guess I do, haven’t had time to look at the notebook and data): `DetailedItinerariesComputer`, by default, does not computer all-to-all matrices (we decided on that in a call in spring), but each row in origins to each row in destinations. If (guessing here) you supply the same data frames as origins and destinations, the requested routes would be from each point to itself

**Comment by christophfink** [comment]
I checked your notebook, and, indeed, you supplied the same data frame (`cgy`) as both `origins` and `destinations`. Could not test the change (`calgary_demographics.gpkg` is missing from the zip file), but I assume commenting out the `destinations=cgy,` would solve the issue

**Comment by christophfink** [comment]
Thinking one step further, we should add a warning to `DetailedItinerariesComputer`, if the supplied origins and destinations are identical and would produce all 0-length routes. Since this happened to you who is rather familiar with r5py, I totally expect this to happen to many users

**Comment by wklumpen** [comment]
Ah I see, I should just put `origins` if I want a square matrix. Yes, considering that slipped my mind I'm sure it will others.
