### ISSUE TITLE
When building docs, do we always want to run the Notebooks?

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#32]
When working with #14, noticed that the requirements.txt for RTD included also r5py related dependencies, here:
https://github.com/r5py/r5py/blob/main/docs/requirements.txt#L17-L27

These are not necessarily needed, if we specify in conf.py that the Notebooks shouldn't be run during the docs building.
But do we want to run the Notebooks always when building the docs? 

The downside of running the Notebooks during every build:
- Building the docs takes longer and consumes unnecessary RTD computing resources
- If there are errors that causes the r5py to fail, these will be immediately visible for users 

The potential good thing in running the Notebooks always:
- If there are errors that causes the r5py to fail, these will be immediately visible for users --> we might be notified about problems sooner

With pyrosm and the educational materials that we have written, we do not tend to run the Notebooks, but I do see the benefit of running them because of the above.

**Comment by HTenkanen** [comment]
No specified in #33 that the Notebooks won't be run when building the docs. Also removed the r5py related dependencies which are not needed now. We can change this behavior if needed.

**Comment by christophfink** [comment]
Running the notebooks always has the huge advantage of not having output artifacts in the notebooks in the repository, and thus much cleaner commits and diffs.

**Comment by HTenkanen** [comment]
Yep this is the case. Not sure though what is the harm of having the artifacts in the history. 🙂 One possible approach dealing with these is to start using Jupytext (we use it in our book project): https://github.com/mwouts/jupytext

**Comment by christophfink** [comment]
> Yep this is the case. Not sure though what is the harm of having the artifacts in the history. slightly_smiling_face One possible approach dealing with these is to start using Jupytext (we use it in our book project): https://github.com/mwouts/jupytext

oooooh! that looks sweeet!

**Comment by christophfink** [comment]
I recently had an issue where jupytext was not called after I had edited a notebook. Not sure what happened, because on that machine I should have jupytext installed.

That said, adding a [pre-commit hook as described in juptext’s documentation](https://jupytext.readthedocs.io/en/latest/using-pre-commit.html) would add additional certainty that notebooks are always up to date, and it provides the additional benefit of working both ways (altering a markdown notebook would also update the ipynb, if I understood correctly).

**Comment by christophfink** [comment]
The pre-commit framework would add a lot of extra dependencies, and would still require user interaction (installing the precommit hook). The cleaner solution would be to run this in the lint/test workflow after pushing.

**Comment by christophfink** [comment]
Okay, this has been a bit of wasted time, see linked branch and all the failed action/worksflow runs. 
For future reference: if a workflow runs on a pull request, the checked out repository is not attached to a branch, but rather runs on detached head. Not sure how to push to the originating repository. I’ll add the reminder tag, again, so I can take a look at this at some point in the future.

**Comment by christophfink** [comment]
https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/

**Comment by christophfink** [comment]
I guess this is okay the way it is now.
