### ISSUE TITLE
Allow strings, lists of strings, and Pathlib obects for `TransportNetwork` OSM and GTFS files

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#335]
`osm_pbf` and `gtfs` can also be passed as `pathlib.Path` or  `list[pathlib.Path]`

**Comment by wklumpen** [comment]
So for a single GTFS file we don't need to use a list?

Handy!

**Comment by christophfink** [comment]
No, that’s not what I meant, although this is a fantastic idea, and should be implemented :D 

The typehints currently look like this accepts `str` and `list[str]`, only, for `osm_pbf` and `gtfs`, respectively (when `str` could also be `pathlib.Path` for both. 

But hell yes, let’s also implement your idea!
