### ISSUE TITLE
Discuss `departure_time_window` in the documentation

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#339]
See discussion in #304

**Comment by wklumpen** [comment]
The question is where does this go - I'm going to propose a "note" or "hint" in the reference for all the variables in the module contents, as well as a brief note in the "travel time matrices" section.

**Comment by christophfink** [comment]
The reference is autogenerated from docstrings, not sure whether you can add fancy formatting into there (but surprise me ;) )
Travel time matrix is definitely the right place

**Comment by wklumpen** [comment]
After seeing some updated discussion on #292 we may want to re-open the issue.
