### ISSUE TITLE
Problem with libjli.dylib not found

### ISSUE THREAD

**Issue by sruinaard** [r5py/r5py#340]
After installing R5py with pip, downloading JDL 11 from the Oracle website (the link in Dependencies is broken) and setting the right location for JAVA_HOME, I cannot get started with the demo of R5py (Helsinki) in my .ipynb file (working in PyCharm, Python 3.11).  

When I run the following (with locally saved data), I get the error stated below. 

from r5py import TransportNetwork

transport_network = TransportNetwork(
    "kantakaupunki.osm.pbf",
    [
        "GTFS.zip"
    ]
)

FileNotFoundError: [Errno 2] JVM DLL not found: /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/lib/libjli.dylib

I have tried to set the right path, and on my mac (OS Ventura 13.0.1) the path and file exist. I have tried to relocate some files (as the file is originally in /lib/**jli**/libjli.dylib), and tried a symlink for the case it needed to be in my user folder instead of the system folder. Unfortunately, these things do not work. What can I do to solve the issue?

**Comment by christophfink** [comment]
This seems to be connected to the upstream [jpype](https://github.com/jpype/jpype/) library. Could you try some of the workarounds proposed there: https://github.com/jpype-project/jpype/issues/994 ?

**Comment by sruinaard** [comment]
I tried the instructions in the last comment and it worked. Thank you Christoph!
