### ISSUE TITLE
Add openjdk as "run" requirement in the conda-forge recipe

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#342]
I believe that if we want that mamba/conda installs OpenJDK automatically when `r5py` is installed, we need to add it as "run" requirement here: [meta.yaml#L22](https://github.com/conda-forge/r5py-feedstock/blob/main/recipe/meta.yaml#L22)

**Comment by christophfink** [comment]
See https://github.com/conda-forge/r5py-feedstock/pull/6

**Comment by HTenkanen** [comment]
@christophfink This seems to work now, so can close this?

**Comment by christophfink** [comment]
yes!
