### ISSUE TITLE
On the `Detailed itineraries` page, it is not clear where all the data should come

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#343]
On the Detailed Itinenaries page, it is not evident where the data for the codes should come from. This is especially the case, if user copy/pastes code snippets directly from our website to separate Notebook on a computer (like I did):

![image](https://github.com/r5py/r5py/assets/6659534/1f8fec02-447c-4fd1-8cb1-087028c32b0f)

Possible solution: Add a visible code cell where the data is loaded, or at least mention it in the text, that the data is the same which was used in the "Quick start".

**Comment by wklumpen** [comment]
I think a full tip-to-toe working version should be included. I assume the population grid can be obtained via the sample data mentioned in #347
