### ISSUE TITLE
Binder link does not work as expected

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#344]
The Binder button on our documentation does not direct correctly to GESIS Notebooks, but it only takes you to the home page of GESIS: https://notebooks.gesis.org/binder/

Something going on probably with the Binder configuration in the [conf.py](https://github.com/r5py/r5py/blob/main/docs/conf.py)

**Comment by christophfink** [comment]
It seems GESIS does not have notebooks themselves anymore, have to revert back to mybinder.org

**Comment by christophfink** [comment]
mybinder.org instances now also have 4 GiB RAM, so the mini examples in our notebooks work okay-ish

**Comment by christophfink** [comment]
Or I don’t get it: I replaced ‘notebooks.gesis.org` with `mybinder.org` in the url of button. That link successfully redirected to a notebook instance, but that instance’s url again is on `notebooks.gesis.org`. Not sure what’s happening, but it seems to work :)
