### ISSUE TITLE
Use `gdf.explore()` instead of contextily in the docs?

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#39]
Could we use the Leaflet functionality of geopandas (i.e. `gdf.explore()`) instead of adding a background map with contextily? This would remove one unnecessary dependency for building the docs.

**Comment by christophfink** [comment]
Sounds good, go ahead!

**Comment by HTenkanen** [comment]
The plotting function based on contextily is also super slow it seems (at least on my computer), so probably also the docs building would be faster

**Comment by HTenkanen** [comment]
Will give this a go.

**Comment by HTenkanen** [comment]
This is now visible in: https://r5py-fork.readthedocs.io/en/issue_39/basic-usage.html

**Comment by christophfink** [comment]
Looks great!
