### ISSUE TITLE
ArrayIndexOutOfBoundsException while using customized OSM.pbf

### ISSUE THREAD

**Issue by jlmalk** [r5py/r5py#407]
**Describe the bug**
I am trying to run r5py on a customized OSM.pbf, which gives me the following Error while setting up the network [r5py.TransportNetwork()]:

> in __init__
>     transport_network.streetLayer.loadFromOsm(osm_file)
> java.lang.java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: Attempt to seek beyond end of edge store

**To Reproduce**
1. Use the pyosmium-lib to filter a given OSM.pbf down to nodes/ways/relations with Key='highway' and Value in ["path", "footpath"].
2. Try to use it to build a network by using the r5py.TransportNetwork() function

**Expected behavior**
There should be no Error...

**Environment:**
 - OS: Win10
 - Python package source: pip

**Comment by wklumpen** [comment]
Hi there!

It's difficult to work through errors with OSM data as they tend to crop up in different ways. 

I suspect that filtering down the OSM data to highways is creating problems when R5 tries to build a network. Have you tried using a complete OSM extract that covers the boundaries of your study area?

BBBike can help you extract that data.

**Comment by jlmalk** [comment]
> Hi there!
> 
> It's difficult to work through errors with OSM data as they tend to crop up in different ways.
> 
> I suspect that filtering down the OSM data to highways is creating problems when R5 tries to build a network. Have you tried using a complete OSM extract that covers the boundaries of your study area?
> 
> BBBike can help you extract that data.

Hey there, sorry for the late reply!

Unfortunately, the study area is the whole of germany, and using the complete OSM extract for that overflows the RAM, even on the server I use...
