### ISSUE TITLE
keep R5 from saving temporary files into input directories

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#44]
Figure out how to make R5 save the .mapdb elsewhere, and not next
to the input files (they could well be on a r/o filesystem, or in a dedicate
data folder that should not be littered with random cache files).

There are (at least) the following three options of doing that:
  1) Use a java agent/instrumentation api to monkey-patch
     com.conveyal.r5.transit.TransportNetwork.fromFiles where the path to the 
     .mapdb file is hardcoded. Not sure how easy that is, and whether jpype
     (properly) supports it. 
  2) Have a patched com.conveyal.r5.transit.TransportNetwork (or com.conveyal.osmlib.OSM)
     in the class path _before_ the r5-all.jar. Easy, but messy, potential maintenance hell.
  3) Copy the input file(s) to a temporary directory before reading them.
     By far the cleanest option, but have to check /tmp disk space (if it’s a ramdisk - the 
     default on most current linux installations - we cut into memory; might have to check how 
     long R5 wants to be able to access input files)

**Comment by Thrameos** [comment]
I would recommend using ASM to mod the jar/class file.   If the symbol name is well defined it isn't hard to alter a constant or change a method.  If it is scattered all over.  

JPype does not support on the fly modification of a jar.

**Comment by christophfink** [comment]
Thanks, @Thrameos!

**Comment by christophfink** [comment]
A fourth option would be to compile our own patched version of upstream R5, but that might also become maintenance hell in the long run.

**Comment by christophfink** [comment]
> using `pathlib.Path.symlink_to()` to link to the original file (_should_ work on Windows, too)

https://www.scivision.dev/windows-symbolic-link-permission-enable/ : ‘Windows users may not have permission to create a symbolic link by default. ’
