### ISSUE TITLE
Should TravelTimeMatrix in fact be named TravelTimeMatrixComputer?

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#51]
see issue title

**Comment by HTenkanen** [comment]
Or should it be, `ComputeTravelTimeMatrix`? Not sure though if we want to have such a long class name in any case..?

**Comment by HTenkanen** [comment]
Ah well then, another question: do we want to stick with this kind of CamelCase naming style? It's very Java, but not that typical in Python.

**Comment by christophfink** [comment]
https://peps.python.org/pep-0008/#class-names

**Comment by HTenkanen** [comment]
Yes, exactly 👍🏻 Ah I probably misunderstood your earlier comment. I.e the TravelTimeMatrix is a class not a function?

**Comment by HTenkanen** [comment]
I thought that you said that these names that we are discussing here would be for a function, not a class

**Comment by HTenkanen** [comment]
And I guess TravelTimeMatrixComputer would contain methods to calculate the matrices hence the name?

A bit more explicit issue / more description in the beginning would have been good here to understand  ;)

**Comment by HTenkanen** [comment]
If this is the case, then TravelTimeMatrixComputer could be a suitable / intuitive name, yes 👍🏻

**Comment by mvpsaraiva** [comment]
Just to give my 2 cents, in `r5r` I've named the classes TravelTimeMatrixComputer, AccessibilityEstimator, ParetoFrontierCalculator and DetailedItineraryPlanner. The ending verbs are kind of arbitrary, but to me they feel a bit "natural" to what they do.

**Comment by christophfink** [comment]
Exactly! Maybe it would be best if we go with the very same class names

**Comment by HTenkanen** [comment]
Sounds good! 💯
