### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#52]
In our environment files and also setup.cfg, there are multiple dependencies that don't need to be there, i.e. numpy, pandas, shapely.
All of those packages are "hard" dependencies of geopandas and will be automatically installed with geopandas.

**Comment by HTenkanen** [comment]
Yes well they might change but it is highly unlikely in this case, so I wouldn't be so strict with this. Geopandas is absolutely never going to drop the dependency from pandas (it's totally built on top of it) and similar case with shapely (everything relies on it). I also don't see that pandas would drop numpy as a dependency anytime soon. 

And after all, if some of these hard dependencies would be dropped (very unlikely), we can then just add the dependency to our environment. If we would rely on specific version of these underlying dependencies of geopandas, then it would be natural to have them here, but that is not the case here. I just see these redundant, and for all these environments there are unnecessary calls and steps done when the environments are created.

**Comment by christophfink** [comment]
But why remove them now?

**Comment by christophfink** [comment]
But the packages should be pulled in explicitly, since we actually use them, also. It's of course a bit of an academic discussion, because in practice the outcome is very similar (also dependency resolving should be very similar in effort). Still, I would assume it best practice to require all dependencies that we import. Of course not dependencies of dependencies (if we don't import them ourselves)

**Comment by HTenkanen** [comment]
Okay, fair enough 👍🏻 But we do not actually import Shapely anywhere in the package (?) , so with this logic I think it shouldn't be in the setup.cfg? We only import it in documentation and I wouldn't count those dependencies in a similar manner as dependencies that the package requires.

**Comment by christophfink** [comment]
I think so, I'll check in the morning

**Comment by christophfink** [comment]
I'll properly grep all import statements and compare it against the requirements

**Comment by christophfink** [comment]
```bash
> grep -hE '^import | from .* import' -r src/ | sed 's/^import //;s/^from \(.*\) import.*$/\1/' | sort | uniq | grep -vE '^\.'
ch.qos.logback.classic
com.conveyal.r5
configargparse
datetime
enum
hashlib
java.io
java.lang
java.time
java.util.ArrayList
joblib
jpype
jpype.imports
jpype.types
json
math
multiprocessing
numpy
org.slf4j.LoggerFactory
os
os.path
pandas
psutil
re
requests
sys
```

You were right, we don't import shapely! :smile:

**Comment by christophfink** [comment]
configargparse
numpy
pandas
psutil
requests

-- 

But: we use both geopandas and shapely as types for function parameters (and in the docs).
