### ISSUE TITLE
Change r5py license to MIT?

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#59]
@christophfink I noticed that you have set the license of r5py to GPLv3. Is this something that you chose specifically or just something that you have used to use?

I see that Conveyals r5 as well as r5r are licensed with MIT, which is more permissive license compared to copyleft GPL family licenses. I think it would make sense to have the same license here for many reasons (e.g. companies tend to avoid GPLv3 license). I would also be happy to see r5py shipped with MIT. 

I think now would be still a good time to do the change before we ship the package to PyPi and conda-forge. 

 Any thoughts @christophfink @rafapereirabr @mvpsaraiva @wklumpen?

**Comment by christophfink** [comment]
I would like have the GPL in there, too, but I’m fine with adding MIT 
(so have a dual-license; I can take care of the LICENSE files)

**Comment by HTenkanen** [comment]
How does it work with dual-license? So the user can decide which one to follow, or? I do not have any experience with such approach.

**Comment by HTenkanen** [comment]
> How does it work with dual-license? So the user can decide which one to follow, or? I do not have any experience with such approach.

See this: https://softwareengineering.stackexchange.com/questions/139663/confusion-about-dual-license-mit-gpl-javascript-for-use-on-my-website

**Comment by christophfink** [comment]
Yes, user can choose
