### ISSUE TITLE
Fix license file naming to follow SPDX identifiers

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#77]
conda-forge linters [complained about our license file naming](https://github.com/conda-forge/staged-recipes/pull/18931#issuecomment-1125711053). Although, we don't need to follow the same naming style as in our conda-forge feedstock repo, I think it still might be good to have identical naming conventions, i.e. we should name:

- LICENSE.MIT --> MIT
- LICENSE.GPL-3.0-or-later --> GPL-3.0-or-later

**Comment by christophfink** [comment]
Would there be the possibility to put them in a sub-directory or so? It seems weird to have a file `MIT` and a file `GPL-3.0-or-later` ...
or maybe is it dependent on the names in `LICENSE`?

**Comment by HTenkanen** [comment]
I guess in r5py repository we can do however we want, so we can create a subdirectory for the license files. For r5py-feedstock repository I'm not sure as they are more strict in the structure of the files. But it doesn't matter really because no-one is going to look at the feedstock repository expect us.

**Comment by christophfink** [comment]
Apparently, it is possible to create a directory `licenses/` and put the detailed licenses in there.
https://github.com/conda/conda-build/pull/3600/files

**Comment by HTenkanen** [comment]
Ah right!

**Comment by HTenkanen** [comment]
Will add them there

**Comment by christophfink** [comment]
and then in meta.yaml, add `licenses/*`

**Comment by christophfink** [comment]
> I guess in r5py repository we can do however we want, so we can create a subdirectory for the license files. For r5py-feedstock repository I'm not sure as they are more strict in the structure of the files. But it doesn't matter really because no-one is going to look at the feedstock repository expect us.

It would be nice to keep everything the same, wouldn’t it? So we don’t have to keep up too much of redundant infrastructure/information

**Comment by HTenkanen** [comment]
> and then in meta.yaml, add `licenses/*`
> 
> Edit: if I read this correctly, then like this:
> 
> ```yaml
> about:
>   license_file: licenses/
> ```

I guess here is the latest documentation, how this should be done: https://github.com/conda/conda-build/blob/master/docs/source/resources/define-metadata.rst#license-file

I.e. we need to have a license statement in `LICENSE` and then the files in `licenses` and the YAML should have (if I interpret this correctly):
```
about:
  license_file:
    - LICENSE
    - licenses/
```

**Comment by HTenkanen** [comment]
We could follow the same convention in r5py?

**Comment by christophfink** [comment]
Yes, sounds good! I can reorganise the repo here, if you take care of the conda end of things

**Comment by HTenkanen** [comment]
Yep, sounds good. 👍🏻 In terms of the license statement, should we have text:

```
GPL-3.0-or-later or MIT
See 'licenses/' directory
```

**Comment by christophfink** [comment]
Is that allowed? then yes

**Comment by HTenkanen** [comment]
I'm not sure about the restrictions here, but I would be slightly surprised if adding this description where to actually find the license files would be not allowed.
