### ISSUE TITLE
Improve basic tutorial

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#80]
(This is on a sidenote, and deserves its own issue, maybe)

We should also try to streamline the story line of the basic-usage notebook, I think first having the grid points, then loading the transport network, might be a better idea.

_Originally posted by @christophfink in https://github.com/r5py/r5py/issues/64#issuecomment-1125801130_

In addition, to this ^, it would be very nice to also show something visual from the results. I.e. create a map showing the travel times to/from specific point.

**Comment by christophfink** [comment]
yes! so, should we still create the same data set with grid cells?

**Comment by wklumpen** [comment]
In terms of visuals, I tend to use [Altair](https://altair-viz.github.io/index.html) for basically everything I do - but of course that requires a separate package installation. MPL might be a better way to go?

**Comment by wklumpen** [comment]
Also I'd be happy to recrate a dataset for another city (just did one for Calgary) or based on what you had if you wanted to do a hexgrid or something like that.

**Comment by christophfink** [comment]
> I do think it should be set up as a warning/exclamation in the documentation for any "Getting Started" documents, since setting the appropriate memory is sort of a big fundamental choice in terms of performance and experience with the system.
> 
> To play devil's advocate: One advantage of making the user set an explicit memory (or at least requiring some sort of call/action to set it up) is that they are made aware that we are sitting on top of a fairly beefy java machine running underneath. My worry is that the 80%/2GB rule might create some problems down the road that are more slippery to diagnose.

https://github.com/r5py/r5py/issues/35#issuecomment-1128063771 by @wklumpen 

> That’s a very valid point. Let’s add a warning to the `basic-usage.ipynb`, so everybody should have read it.

https://github.com/r5py/r5py/issues/35#issuecomment-1128082355 by @christophfink

**Comment by christophfink** [comment]
> Also I'd be happy to recrate a dataset for another city (just did one for Calgary) or based on what you had if you wanted to do a hexgrid or something like that.

I guess it would be nice to have another dataset for some of the more advances tutorials we will be writing, but no hurries with this. We’ll also have to make sure that we keep all sample files nice and small (and GTFS are huge!).

**Comment by christophfink** [comment]
> In terms of visuals, I tend to use [Altair](https://altair-viz.github.io/index.html) for basically everything I do - but of course that requires a separate package installation. MPL might be a better way to go?

Never used it TBH. For the time being, I guess we’re fine with what `geopandas` and pandas do by default, but making things look nicer is always great :)

**Comment by wklumpen** [comment]
I'll probably put a Calgary-focused post up on the website once we do a launchy-launch thing with some pretty pictures so I can go hogwild then.

**Comment by wklumpen** [comment]
Based on our discussion, I propose the following three sections in a basic tutorial:

* A simple "make a travel time matrix from a set of dots" using Helsinki and São Paulo data
* Using the results above to do a basic access calculation using the destination counts for the two data sets
* Using an `expanded_travel_time_matrix` in some way (ideas?)

**Comment by HTenkanen** [comment]
@christophfink Yes, I have advanced with this and will now work on this. Aiming to get this done in the coming hours..
