### ISSUE TITLE
Add artwork (until now only the logo) to the repository

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#82]
maybe into `assets` or `images`, or somewhere inside the `docs` 

also:

- [x] add it to the README
- [x] use it as the avatar for the github organisation

@HTenkanen , I guess you have the source files?

**Comment by christophfink** [comment]
Oh and yes, I’m aware that the .png is inside docs/_static

**Comment by HTenkanen** [comment]
@christophfink : Ah only now noticed this. Yes, I have the source files. Did it very quickly with CorelDraw, i.e. I have the `*.cdr` file, but I can export the things from there to any format. Which format should I export this to? Svg? Pdf?

**Comment by HTenkanen** [comment]
Inkscape can also read CDR files without a problem (in case you're using that)

**Comment by christophfink** [comment]
SVG would be most universal, I guess?

**Comment by HTenkanen** [comment]
Closed by #158
