### ISSUE TITLE
jvm.py missing elif / else statement

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#88]
@christophfink Question: there is this `if not` statement here: https://github.com/r5py/r5py/blob/1ed9dba046fe9c50adaac21bdef45e8cd69583a8/src/r5py/util/jvm.py#L26

But the code seem to miss the alternative logic, ie what should happen in other cases? Just spotted this and started wondering.

**Comment by christophfink** [comment]
The default is the else: print all the warnings.
The logic is: if user chooses non-verbose output, block a bunch of Java logging
No need for an else

**Comment by HTenkanen** [comment]
Okay, makes sense 👍🏻

**Comment by christophfink** [comment]
Sorry for reopening this: should the default be verbose output or quiet output? (Currently: quiet)

**Comment by HTenkanen** [comment]
@christophfink I'd say quiet output. We might actually want to document this in the docs as well. There could be a separate section about different configuration options where we collect some tips to typical aspects a user might want to configure?

**Comment by HTenkanen** [comment]
Created a new issue about the docs. Closing this now.
