### ISSUE TITLE
A separate section for different configuration options 

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#90]
@christophfink I'd say quiet output. We might actually want to document this in the docs as well. There could be a separate section about different configuration options where we collect some tips to typical aspects a user might want to configure?

_Originally posted by @HTenkanen in https://github.com/r5py/r5py/issues/88#issuecomment-1126637207_

**Comment by christophfink** [comment]
There is such a section, BTW, in the installation.rst. but given that we should also explain more about JVM memory limit and custom R5 jars, let's create a separate file

**Comment by HTenkanen** [comment]
Yep, I think it would be better to have a separate page because there will likely be many things that would be good to explain for the user (also considerations related to accessibility calculations).
