### ISSUE TITLE
R5 Hash assertion always fails

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#91]
It appears the assertion that checks the hash in `util/classpath.py` always fails and an R5 Jar is therefore always downloaded.

At first I thought it was simply that we were calling `.hexdigest` isntead of `hexdigest()` (pull request incoming for that change) but even after that fix the `AssertionError` is thrown and the file is re-downloaded.

I checked the hash strings and they are equal so I'm not sure why the `AssertionError` is being thrown at all since the strings should be equal.

```
Jar hash: 9e4ceb85a09e750f146f95d98013eb164afac2dfc900a9e68e37ae925b1ec702
Our hash: 9e4ceb85a09e750f146f95d98013eb164afac2dfc900a9e68e37ae925b1ec702
```

However pulling the string as a variable and then doing the assertion seems to work fine:

```python
with open(R5_CLASSPATH, "rb") as jar:
            our_hash = hashlib.sha256(jar.read()).hexdigest()
            assert our_hash == R5_JAR_SHA256   # Does not fail assertion
```

So I'll suggest that change.

**Comment by HTenkanen** [comment]
Added a [comment about this here](https://github.com/r5py/r5py/pull/92#issuecomment-1126889001) that might perhaps explain something (or not).
