### ISSUE TITLE
Convert time-zone aware `departure` `datetime`s to the GTFS timezone

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#93]
Seems almost silly to ask, but I wanted to confirm that passing a timezone-naiive datetime will indeed consider local time departures for the travel time matrix computations.

**Comment by christophfink** [comment]
No, that's a restriction of R5, it always assumes the datetime is in the timezone of the GTFS data set (cf. https://ipeagit.github.io/r5r/reference/travel_time_matrix.html )

**Comment by christophfink** [comment]
But we could handle this, of course: if timezone is specified, convert from that timezone to the GTFS timezone, otherwise assume local.

**Comment by christophfink** [comment]
https://docs.python.org/3/library/datetime.html#aware-and-naive-objects

**Comment by wklumpen** [comment]
Some potential complications:
* Cracking open the GTFS file(s) might be a step more than we want, unless we can retrieve what timezone R5 is using after building the network
* It's technically possible to have an analysis [span two time zones](https://www.usatoday.com/story/news/world/2016/12/14/cyprus-two-different-time-zones/95197044/)

**Comment by christophfink** [comment]
R5 has the GTFS zone exposed somewhere, let me check

**Comment by christophfink** [comment]
Actually, I already wrapped that into a Python property: `TransportNetwork.timezone` https://github.com/r5py/r5py/blob/main/src/r5py/r5/transport_network.py#L120 

That is a `java.time.ZoneRegion`, though, and I’m not sure how to get the offset from UTC from it (the name seems easy, and then looking that up from `pytz` should work)

**Comment by christophfink** [comment]
> Some potential complications:
> 
>     * Cracking open the GTFS file(s) might be a step more than we want, unless we can retrieve what timezone R5 is using after building the network
> 
>     * It's technically possible to have an analysis [span two time zones](https://www.usatoday.com/story/news/world/2016/12/14/cyprus-two-different-time-zones/95197044/)

We could also put this on hold, for now, and stick with the way r5r handles it: just always assume `departure` is in the GTFS data’s time zone

**Comment by wklumpen** [comment]
I think we leave it, as R5 does the "appropriate" thing I think.
