### ISSUE TITLE
Define the conventions we use for importing classes

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#95]
Add to the CONTRIBUTING document as section that details the conventions we use for importing classes (e.g., *full* module path for external dependencies (because Java classes), order of import statements (built-in library, python deps, local modules, java deps), ...)

**Comment by HTenkanen** [comment]
As a reference, see [this discussion](https://github.com/r5py/r5py/pull/85#pullrequestreview-973506645)

**Comment by HTenkanen** [comment]
Resolved by #96. 

A section can be found at: https://r5py.readthedocs.io/en/latest/CONTRIBUTING.html#import-order-import-of-submodules
