### ISSUE TITLE
DOC: Shorten the code of conduct title?

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#97]
A minor thing but now after seeing the build docs, the code of conduct title is a bit long taking two lines on the navigation panel. Could it just be `Code of conduct`?

![image](https://user-images.githubusercontent.com/6659534/168747597-7ba46d91-2679-4309-bb07-aba87175eaa5.png)

**Comment by christophfink** [comment]
I would agree to shorten the anchor text in the navigation panel (I guess that can be done independently from the title in the file?)
